### ISSUE TITLE
Unstaking time is unclear

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1022]
There is nowhere informing in the UI that it will take ~36 hours to unstake when staking.

**Comment by kcole16** [comment]
@Patrick1904 Did we remove this from the modal?

**Comment by Patrick1904** [comment]
![Screen Shot 2020-10-14 at 9 17 29 AM](https://user-images.githubusercontent.com/24921205/96017769-3e6bb600-0dff-11eb-9b86-727996db95dd.png)
![Screen Shot 2020-10-14 at 9 17 19 AM](https://user-images.githubusercontent.com/24921205/96017773-3f044c80-0dff-11eb-8741-5c8697af7bf8.png)

Yes we only have this right now but will add to the modal too so that users don't miss it.

**Comment by corwinharrell** [comment]
Recommending changes to our success state in the staking UI to inform about the release period:

<img width="956" alt="Screen Shot 2020-10-14 at 12 48 19 PM" src="https://user-images.githubusercontent.com/5934188/96020222-b0ea8f00-0e1b-11eb-92c4-889e3a4479bf.png">

This same copy and treatment is being introduced for unstaking in #755

**Comment by Patrick1904** [comment]
> Recommending changes to our success state in the staking UI to inform about the release period:
> 
> <img alt="Screen Shot 2020-10-14 at 12 48 19 PM" width="956" src="https://user-images.githubusercontent.com/5934188/96020222-b0ea8f00-0e1b-11eb-92c4-889e3a4479bf.png">
> 
> This same copy and treatment is being introduced for unstaking in #755

Looks good to me. Is it worth showing this disclaimer before confirming the stake, vs after?
