### ISSUE TITLE
Email/phone recovery doesn't work for some implicit accounts

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1121]
**Problem**
During account creation, users can exit the flow early during the funding step, and will get stuck if they've chosen email recovery (because the account name is incorrect/doesn't exist yet).

**Expected Behavior**
Users should be able to recover with email at all times, even if they've not yet created the named account.

**Steps to reproduce**

1. Go to `/create`
2. Enter a username
3. Choose email/phone recovery and verify your email
4. Record your implicit account and exit the page
5. Fund the implicit account
6. Try to recover with the email/phone link

The link will display "Link is invalid". This is because the account name in the URL was never created, as the user ended the flow too early. Recovering with the seed phrase in the account will work, since it looks up the correct account name (the implicit account).

**Comment by vgrichina** [comment]
@kcole16 not sure what is the best solution in terms of UX here.

Search for all accounts using seed phrase if specific one wasn't found?

**Comment by vgrichina** [comment]
@kcole16 @corwinharrell 

> Search for all accounts using seed phrase if specific one wasn't found?

Does this make sense for you as a fix or should we do anything else?

**Comment by corwinharrell** [comment]
A couple things I noticed within this flow:

1. On the `Fund Account` page, when I click `Copy Account ID`, the success toast that gets displayed says `Seed Phrase Copied`. Seems like an incorrect translation reference here?

2. When I attempt to recover my funded account via my email link before the named account has been created, I get an error that says `No accounts were found for this seed phrase`. This won't make sense to a user who elected to set up their account with email recovery, since they never chose a seed phrase option at any point. Why are we referencing Seed Phrases anywhere if the user chose to set up their account with email?

@vgrichina I'm not quite sure what you mean by this:
> Search for all accounts using seed phrase if specific one wasn't found?

Do you mean other accounts for which the user is the owner?

**Comment by kcole16** [comment]
@vgrichina I think the best solution is to search all accounts for the phrase first, and if none are found, try to use the one in the URL.

We could consider not handling this (if we suspected it may cause other issues), as we should try to prevent users from needing to recover the implicit account. Seems like it will happen at least occasionally though

**Comment by Patrick1904** [comment]
Closing as issue is outdated
