### ISSUE TITLE
Improve "Available Balance" clarity

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1129]
### Overview
We've had some confusion about the `available balance` since we've subtracted the 2N "tolerance". 

While we work on a more complete solution, we should remove the 2N "tolerance", and display the `available balance` like before.

### Acceptance Criteria
- [ ] `available balance` = `actual balance` - `minimum balance`
- [ ] Remove "Use Max" from staking flow
- [ ] If user enters an amount > `available balance` - 0.1 N, they receive an error
   - [ ] `/staking`
   - [ ] `/send-money`

**Comment by vgrichina** [comment]
> If user enters an amount > available balance - 0.1 N, they receive an error

hmm, doesn't it just mean changing minimum balance from 2N to 0.1 N? Or am I missing something?

I think part of the problem is that there is also actual minimum balance (i.e. locked for storage), for this reason some math was off. + generally we are pretty off with info on staked tokens

**Comment by corwinharrell** [comment]
@kcole16 in the scenario where a user inputs an amount equal to `Available balance` - `0.1N`, the transaction is guaranteed to fail is it not?

**Comment by kcole16** [comment]
@corwinharrell Why would it fail? The idea is that the 0.1N should be sufficient to cover gas costs (at least in most cases). If they input their actual full account balance, then it would fail.

**Comment by corwinharrell** [comment]
Sorry @kcole16 I meant to say greater than, not equal to:

My reason in asking is that we can simply disable the Stake/Send submission buttons if the amount exceeds `Available balance - 0.1N`, and display a simple message inline, rather than showing a more obtrusive warning once they've submitted.

**Comment by corwinharrell** [comment]
@Patrick1904 @vgrichina @kcole16 @mattlockyer Curious to know what you guys think of this approach:

![Network Fees](https://user-images.githubusercontent.com/5934188/98023350-c9bfe200-1dd4-11eb-9a84-cb255365a906.gif)

**Comment by Patrick1904** [comment]
> @Patrick1904 @vgrichina @kcole16 @mattlockyer Curious to know what you guys think of this approach:
> 
> ![Network Fees](https://user-images.githubusercontent.com/5934188/98023350-c9bfe200-1dd4-11eb-9a84-cb255365a906.gif)

@corwinharrell I think this solves the issue quite well. A lot of users want to stake their full available amount, and making that easy and clear would be optimal IMO. Ideally, we'd prevent users from getting into a semi-error state (alt color maybe). However this solution does help educate users about the required minimal balance.

Another option that would allow us to keep the 'Use max' button might be:
1. Show actual available balance (no padding etc)
2. User clicks 'Use max' -> fills input with available balance - 0.1N
3. Shows a label (or banner like your design) explaining that 0.1N must be reserved

**Comment by corwinharrell** [comment]
@Patrick1904 you must read minds cause I'm prototyping that variation as we speak 👌

**Comment by corwinharrell** [comment]
Given @Patrick1904's brief breakdown above, there is also the option to keep the `Use Max` function, and to provide 3 alternate states depending on the actions taken by the user when staking or sending funds (let's keep in mind that the _**ideal**_ scenario would be for us to display a cost breakdown where we show the actual calculated cost of the transaction, and that this solution would exists until we were able to make the changes necessary to display that amount)

Scenario 1: The user enters an amount `=< Available Balance - 0.1 N`

Scenario 2: The user clicks `Use Max`. In response, we populate the input with the amount of `Available Balance - 0.1 N` and display a brief message explaining why `Max !== Available Balance`

Scenario 3: The user manually inputs an amount `> Available Balance - 0.1 N`. Manually adjusting the amount or pressing `Use Max` resolves this, and enables the Submit button.


<img width="1392" alt="Screen Shot 2020-11-03 at 3 23 42 PM" src="https://user-images.githubusercontent.com/5934188/98037307-5bd1e580-1de9-11eb-84d2-ad3bbdbefa2e.png">

**Comment by vgrichina** [comment]
Some quick evaluation of other wallets:

- seems like Trust Wallet displays "Avaiable Balance" as main balance and then has separate number when you are trying to send
- Math Wallet just shows full balance everywhere. When you try to send full balance you get "Server error".

**Comment by vgrichina** [comment]
Moonlet I cannot test on my iPhone SE unfortunately as a form to enter seed phrase doesn't fit screen :(

**Comment by mattlockyer** [comment]
In terms of contract storage amount used I'd like to clean that up as well. The real fix for those that want to completely destroy and migrate out of an account doesn't exist at the protocol level.

Enable/disable is in my latest PRs which gets users to all but ~2 N available.

**Comment by vgrichina** [comment]
> The real fix for those that want to completely destroy and migrate out of an account doesn't exist at the protocol level.

@mattlockyer not sure what do you mean. You totally can delete account on protocol level and claim all the tokens locked for storage.

**Comment by kcole16** [comment]
@vgrichina Moonlet's implementation is somewhat similar to the one proposed here:
- Only one balance "All balance"
- Can select "Max", which enters a value of `"All balance" - 0.001 NEAR`
- If you enter the exact full balance, you get an error "Insufficient balance for fees"

**Comment by vgrichina** [comment]
Options we have:

1. reduce min balance without changing logic (solves main problem with 2 NEAR, inconsistency with Moonlet?)
2. ship current change (solves problem with 2 NEAR, introduces problem with not being able to spend "available" balance)
3. hide "available balance" altogether, at least with Send / Stake, until we have "use max"
4. current change, but "available balance" redefined to adjust for gas need to send one last transaction (so that you actually can send. Potential problem is that account will be non-recoverable until you add funds)
5. current change + "use max"

@corwinharrell @kcole16 @Patrick1904 please rank these options in terms of how desirable from your POV

**Comment by Patrick1904** [comment]
I think either 1 or 5. Both clearly come with some drawbacks and I can't say that I prefer one over the other.

**Comment by mattlockyer** [comment]
**Regarding @vgrichina options 1-5:** 

Ranked in desirability **5,4,2,1,3**
assuming current change is @corwinharrell warning banner?

**Destroying Account and Transfer Max:**

I realize this is tangential to available balance for staking, but something users may be trying to do at a higher level when they want to "transfer max".

> @mattlockyer not sure what do you mean. You totally can delete account on protocol level and claim all the tokens locked for storage.

@vgrichina ahhh I see that now. I'm confused because there is no way to delete contract and storage. I assumed falsely there was no way to delete account. Checked nomicon.

@kcole16 @vgrichina what do you think about offering this as an option for transfer? Completely destroy account and migrate balance to new account?

**Comment by corwinharrell** [comment]
Favored solution in response to some great user feedback received via Twitter (most of whom are from Ethereum):

> Show full balance. Allow me to select "max" or "all", display balance X, minus fee y, equals z send amount. 
Hiding/abstracting fees At the moment is potentially confusing because of the volatility of the fee. May always be better to show fee anyway for transparency/education.

> Maybe a change in button language might help "Send max" vs "Send all"

### Summary
- Show actual available balance (ie no subtractions to account for anything)
- Allow "Send Max"
- When user chooses "Send Max" input the amount minus the transaction fee (or in our case, whatever padding we are subtracting)
- **Key addition:** Before the user submits the transaction, show the math. Display the available balance, show the amount reserved, and show the amount that is actually being sent.

**Comment by corwinharrell** [comment]
@vgrichina @kcole16 @Patrick1904 @mattlockyer feedback welcome

<img width="1092" alt="Screen Shot 2020-11-11 at 12 57 34 PM" src="https://user-images.githubusercontent.com/5934188/98847022-c0122c00-241d-11eb-8007-dbc633f9f7ba.png">

**Comment by Patrick1904** [comment]
@corwinharrell I think this looks good. The main thing still missing IMO is a way for the user to know what their actual 'available balance' is within this context, i.e. not having to calculate it. If the user decides to enter the amount manually.

Initially, I thought the 'reserved for fees' amount had been deducted from the 'available balance'

**Comment by corwinharrell** [comment]
Does this communicate better?

<img width="1070" alt="Screen Shot 2020-11-11 at 1 29 24 PM" src="https://user-images.githubusercontent.com/5934188/98849910-f2be2380-2421-11eb-8489-9af4bceed2b9.png">

**Comment by Patrick1904** [comment]
@corwinharrell yes I like this a lot!

**Comment by Patrick1904** [comment]
Something to take into consideration is that this would introduce the concept of TX fees for all users staking/sending, not just in the 'Use max' case. Currently it seems our 'reserved amount' will be around 0.35N. And users might think that the whole amount will be used to cover TX.

**Comment by corwinharrell** [comment]
@Patrick1904 yep that's something we should definitely keep in mind. I think the problem that this stems from is the fact that at the moment, we don't actually have a way to calculate actual txn costs, which is a shortcoming of ours for sure.

**Comment by Patrick1904** [comment]
Also, this is probably not an issue while staking, but it's slightly confusing if I want to send you exactly 10N, since I'd like to just enter 10N and assume that's exactly what you're going to get.

**Comment by corwinharrell** [comment]
@Patrick1904 yeah that's fair and is something to think about, but IMO is the same conundrum that people encounter when they get to the register with a $5 bill to try and buy something with a price tag of $4.99, only to find out that taxes are 25cents. (Cue bashing of US sales tax, which is entirely warranted)

**Comment by Patrick1904** [comment]
> @Patrick1904 yeah that's fair and is something to think about, but IMO is the same conundrum that people encounter when they get to the register with a $5 bill to try and buy something with a price tag of $4.99, only to find out that taxes are 25cents. (Cue bashing of US sales tax, which is entirely warranted)

Yes, it's a terrible system. I know we don't want to introduce more 'balances', but it would simplify things greatly if we did show a contextual 'available balance', and still keep the 'reserved for fees' row below. Omitting the 'total stake' row. That way, the 'available balance' you see is what you can use, and what you enter is exactly what you'll send. If you add up the 'Available balance' and the 'reserved for fees' amount, you'll get the 'available balance' displayed on `/profile`. Personally I wouldn't find that confusing, but not sure about other people.

**Comment by corwinharrell** [comment]
@Patrick1904 I'm on board for that solution, but would urge that we be intentional about the language that we use and say "Available to send" on this view. That way `Available to send + Fee reserve = Available balance`, which seems to be just about as straightforward as we're going to get until we are able to calculate the actual cost of txn fees dynamically.

**Comment by corwinharrell** [comment]
Here's an example of the above proposed solution:

<img width="978" alt="Screen Shot 2020-11-16 at 11 26 31 AM" src="https://user-images.githubusercontent.com/5934188/99280020-e1e52780-27fe-11eb-9f4f-95f665050e6b.png">

**Comment by Patrick1904** [comment]
@corwinharrell I fully agree. I'll implement this once the user tests checks out.

**Comment by Patrick1904** [comment]
Also, @vgrichina @kcole16 @mattlockyer do we all agree that this is the best approach? Assuming user tests check out.

**Comment by corwinharrell** [comment]
Quick update: I'm in the process of scheduling participants to test with near the end of this week as a followup to the sprint, and will be validating this direction as a component of the next iteration of the staking flow.

**Comment by vgrichina** [comment]
> Also, @vgrichina @kcole16 @mattlockyer do we all agree that this is the best approach? Assuming user tests check out.

yeah, I think this makes most sense

I only wonder whether we should pre-populate default value vs having 0 by default for staking. There are 2 options here:
1) optimize for staking max amount
2) optimize for fast withdrawals of rewards (e.g. leave about 1% unstaked)

**Comment by corwinharrell** [comment]
Alright gang, here is the latest iteration of the staking (and new send) flow. The key difference here is we would default to showing `Available to Stake`, and allow the user to expand the details of this figure below the `Amount` field, where we display the breakdown of `Available Balance - Fee Reserve = Available to Stake`. This creates an experience where users can always see the explicit amount available to stake, and if they are curious about how this figure is calculated, can view the breakdown for more details. This design leaves very little room for questions, save for what the user is actually being charged for the transaction (which we are currently unable to calculate).

In the future if necessary, we can add the actual txn/gas fee to the confirmation screen in an attempt to be even more transparent.

![Kapture 2020-11-19 at 15 15 36](https://user-images.githubusercontent.com/5934188/99719919-f7ff1c00-2a7a-11eb-8abd-9ced9fb0a452.gif)

@vlad in response to pre-populating the field, I'm of the opinion that we don't want to make any assumptions about the users intent regarding the amount they want to stake. The `Use max` feature makes it easy enough for them to stake all of what they have available, but still leaves the decision in their hands, rather than making any decisions for them.

**Comment by Patrick1904** [comment]
@corwinharrell can you please add a screen for `/send` too since it includes entering the receiver account ID. Same Figma file would be great.
