### ISSUE TITLE
Make it clear implicit account is temporary during account creation

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1130]
### Overview
We've had multiple users accidentally send 2+ transactions to their temporary implicit account, including after it was deleted. 

We need to make it clearer that the implicit account should only be used once.

![Screen Shot 2020-11-02 at 10 02 51 AM](https://user-images.githubusercontent.com/5624527/97902617-b3415a00-1cf2-11eb-8a36-f8dec5d59fa6.png)

**Comment by corwinharrell** [comment]
@kcole16 are the transactions the users are sending just attempts to ensure that they are funded?

**Comment by kcole16** [comment]
@corwinharrell In each of the three cases I've seen, the users 
1. Sent ~3 NEAR to their temporary implicit accounts
2. Clicked "Continue", deleting the implicit account, and transferring the balance to the new named (.near) account
3. Sent a much larger amount of NEAR to the now deleted implicit account (which thankfully "restores" it, and I was able to walk them through recovering it)

**Comment by kcole16** [comment]
I'm thinking something like this + additional copy on the "Continue" screen would be helpful

<img width="549" alt="Screen Shot 2020-11-02 at 11 16 16 AM" src="https://user-images.githubusercontent.com/5624527/97928609-45118d00-1d1c-11eb-8937-439805340921.png">

**Comment by corwinharrell** [comment]
@kcole16 I'm just trying to understand #3 a little better ie the motivation behind their decision:

>Sent a much larger amount of NEAR to the now deleted implicit account (which thankfully "restores" it, and I was able to walk them through recovering it)

**Comment by kcole16** [comment]
Seems like they think the implicit address is permanently valid, and that it is the same as the named address

**Comment by vgrichina** [comment]
@corwinharrell @kcole16  Looks like another common issue is that users don't wait enough for transaction to complete on exchange side (e.g. at least one user had such problem).

No idea why any exchange takes more than 6 seconds to withdraw NEAR though, but it is a problem in practice.

**Comment by corwinharrell** [comment]
> Seems like they think the implicit address is permanently valid, and that it is the same account as the named address. They fully expected to see the balance in their .near account.

First of all, this makes a lot of sense, especially coming from Ethereum, where I can have an ENS domain which is simply an abstraction on top of a regular `0x` address, where a user can use either/or to send or receive funds, since they represent the same account.

If this is the mental model some users are used to operating under, it's likely they think that the implicit account is simply the raw address associated with the final named account that gets created (when in fact it is 2 separate accounts that are being created).

We should find out more about these users' motivations. Is this the reasoning behind the behavior? It would be worth following up with users who have encountered this scenario to find out more about their logic to help inform our decisions regarding account creation.

_Aside: I've noticed that the provided designs for #1056 were never actually implemented? These changes were meant to provide some clarity in this scenario. Regardless, they can be improved further given what we are seeing._

I know that technically, what we are asking the user to do here is to first fund a temporary account, which then ultimately gets replaced by their final named account. A couple thoughts:

1. It doesn't seem to benefit them in any way to know that this is a temporary/implicit _**account**_... Saying `Your one-time use account...` isn't very practical for them, and likely introduces more questions than it answers.

2. When the named account is ready to claim, we persist the implicit address. I don't think this makes much sense and may also be contributing to the fact that users are sending additional funds to this address. If the new named account has been funded, that's the ID that we should display on the `Claim` step.

In general, I suggest we frame this process a bit differently. Rather than talking too much about a temporary / one-time use account, let's abstract some of that away and just treat this as a necessary step to fund their final, named account. This might look something like the following:

![Fund Account](https://user-images.githubusercontent.com/5934188/98017136-d5a7a600-1dcc-11eb-9fe5-4fe6ebb89d64.jpg)

**Comment by kcole16** [comment]
@corwinharrell I like this direction. I've asked the three users for more details into their motivations, will report back once I have it.

Another approach (though higher lift) is to move the account name selection to the end. The flow would then be these steps:

1. Select recovery method 
2. Verify recovery method
3. Fund implicit account
4. Optionally, create a named account

This might make it even clearer that the account is now a named account, and also present the user the option to stick with the more anonymous implicit account.

**Comment by corwinharrell** [comment]
@kcole16 I like that as an alternative. Might be worth testing a prototype with a few folks.

**Comment by kcole16** [comment]
@Patrick1904 @marcinbodnar Can we implement @corwinharrell's changes above ASAP? We can discuss further improvements separately, but given the number of users hitting this (five confirmed now), I think we need immediate updates as well

**Comment by Patrick1904** [comment]
> ![Fund Account](https://user-images.githubusercontent.com/5934188/98017136-d5a7a600-1dcc-11eb-9fe5-4fe6ebb89d64.jpg)

@kcole16 I can implement this now. I also suggest we adjust the copy around the amount. Is 3N the absolute minimum? Seems quite high. Also, "_at least_" may be risky. I would think we'd want the user to send a very small amount to this address to 'test it'. Anyway, can adjust the copy anytime, not blocking to implement.
