### ISSUE TITLE
Large js gets redownloaded on reopening the page

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1316]
Currently on almost every load of the page, 700kb+ of JS gets redownloaded.
On not very fast internet Wallet can take up to 15s to load (google.com loads in 4s), reloading another ~5-10s

<img width="484" alt="Screen Shot 2020-12-22 at 5 46 06 PM" src="https://user-images.githubusercontent.com/175486/102949701-bd274400-447d-11eb-8385-53adb6598bfc.png">

From China it's even worse:

<img width="578" alt="Screen Shot 2020-12-22 at 5 50 19 PM" src="https://user-images.githubusercontent.com/175486/102949881-32931480-447e-11eb-8bc7-5c407bd9c1bf.png">

# Steps to reproduce

1. Open incognito window
2. Open Inspect > "Network" tab
3. Open wallet.near.org
4. Observe loading >1Mb of data
5. Refresh wallet.near.org
6. Observer re-loading >1Mb of the same data

**Comment by vgrichina** [comment]
700k of JS is not a lot these days, e.g. Twitter loads more than 1 MB of JS.

> Currently on almost every load of the page

this isn't the case for me in either Safari or Chrome. It has etag so any browser properly supporting HTTP shouldn't be re-downloading whole file unless it is updated

maybe it is somehow messed with by firewall though? (not clear how without removing HTTPS)

are you sure it happens outside of incognito (which has to reload everything as otherwise you are identifiable)?

**Comment by stefanopepe** [comment]
I will embed this one in #1101 , even if not strictly connected I believe that having a smaller payload is better than just pumping everything through CDNs
cc @MaximusHaximus

**Comment by think-in-universe** [comment]
The JS files are not re-downloaded in my test. 

The 800+ KB JS file is fast to load in my environment, but still takes 20~40 seconds for some users. 

![image](https://user-images.githubusercontent.com/46699230/121727649-c042e900-cb1e-11eb-9b67-34056c2534ed.png)
