### ISSUE TITLE
Wallet Selection page

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1425]
There are already more than one wallet and the number will be growing that support signing NEAR transactions.

We ideally want to offer users an option when they click "Log in" or trying to sign a transaction.

There is more work on how to add this option on the App side, via some form of wallet selection there.

But for any wallet that supports linking (or later QR codes), we can also offer selection process on the NEAR Wallet side.

E.g. when user presses login, sign transaction or receives a link drop they are presented with the choice which wallet to use.

This can be similar to such page on an invite link site https://matrix.to: 
<img width="876" alt="Screen Shot 2021-02-07 at 3 46 36 AM" src="https://user-images.githubusercontent.com/175486/107145531-17c61380-68f7-11eb-9c44-4c43620c5133.png">

There are questions around how to ensure that listed wallets are secure.
Wallet should also remember if user already selected one and redirect them to it.

It's important that this page is well CDNed so it's quick to load (e.g. way faster than current wallet loading in China), so ideally a static page would be the best.

**Comment by think-in-universe** [comment]
The wallet selection is definitely a quick win when the number of wallets growth. The wallet selector is commonly used in Ethereum DApps. 

![image](https://user-images.githubusercontent.com/46699230/107154494-26233680-69ae-11eb-8cc1-2a2901844b2b.png)

@marco-sundsk 's initiative https://github.com/marco-sundsk/near-wallet-selector could help. 

The wallet selection solution might also serve as a workaround to the wallet page loading issue in China by providing a CN wallet page as a choice, though I would strongly prefer resolve that issue by enhancing the CDN as suggested here: https://github.com/near/near-wallet/issues/1101

**Comment by marco-sundsk** [comment]
To be as shine as the kickback UI pasted by @think-in-universe , there is still a long way to go. For kickback, it is the dapps responsibility to recognize those wallets. That is to say, kickback as a dapp, it knows how to interact with those different wallets, using different interfaces supported by each wallet. That also means the Select page in kickback is an intrusive one, dapp knows every wallets in its selection, even the whole selection page is an inner part of the dapp.   

While our first version of selector page, aims to be a non-intrusive one. That is to say, neither wallets nor dapps need to know each other or aware of the existing of this selector.  This non-intrusive feather comes with a price. That is, dapps and wallets must communicate with each other through a standard interface. For now, it is the interface implied by official web wallet. That means the diversity of wallets supported by this selector is limited, we can not have chrome plugins nor mobile wallets in this version of selector page.    

But, no matter what, a selector page is definitely a good start, and all its drawbacks can be resolved by upgrading time by time. For example, with the work of near-wallet-SDK, it may become a new standard that can enable plugins and mobile wallets to be included in the selection page in a near future.

**Comment by marco-sundsk** [comment]
From my point of view, the selector page has three job to do:  

First, it should get wallets info from a secure place. For this version, we use on-chain contract as the source of information. And the management of this contract can be restrict to special org, like the Fundation or other intuition. And there may have a whole apply-verify action process behind.  

Second, there would be a clear communication interface of accessing wallets, that enables the selector page to relay all requests from wallet users. For this version, we would take the web wallet interface as our standard.  

Last, the selector itself must be accessible worldwide and as quick as possible. it can be done with a pure frontend, and more than that, this frontend has a very small index page which put all big static files (images and js) on several CDNs. The index page can automatically inspect the speed to each CDN, and always using the fastest CDN as user open it. Besides all those skills, we may also use different nodes to access on-chain contract due to the user's location, if we can get that kind of information.

> There are questions around how to ensure that listed wallets are secure.
> Wallet should also remember if user already selected one and redirect them to it.
> 
> It's important that this page is well CDNed so it's quick to load (e.g. way faster than current wallet loading in China), so ideally a static page would be the best.

**Comment by jimmy3dita** [comment]
@kcole16 if you are good, this may fall within the SDK workgroup, and have the wallet as a "consumer" of the API.

Feel free to close and link any content if you agree

**Comment by agileurbanite** [comment]
Closing this as this was created here: https://github.com/near/wallet-selector
