### ISSUE TITLE
Claiming NEAR drop into existing account

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1467]
**Problem**
If user receives NEAR drop, Wallet forces them to create new account even if they already have an account.

**Expected Behavior**
If user already has an account it shows "Claim X NEAR" and selector for accounts or suggestion to create new one.
If selected existing accounts - Wallet calls `claim` method to directly move funds to the selected user's account.

**Steps to reproduce**

1. Create redpacket
2. Open it yourself
Observe that it requires you to create new account.

**Comment by jimmy3dita** [comment]
@Patrick1904 do we have everything is needed on the code and API side to enable this conditional flow? Do you see any blockers?

**Comment by Patrick1904** [comment]
> @Patrick1904 do we have everything is needed on the code and API side to enable this conditional flow? Do you see any blockers?

This should be pretty straight forward from an implementation stand point. We could re-direct NEAR drop users to a separate page where they can choose to either continue and create a new account, or claim the NEAR drop to their selected account. cc @corwinharrell

**Comment by jimmy3dita** [comment]
Awesome, I will include this improvement in the next sprint - as the red packets are flowing now and it seems to me a missed opportunity.

**Comment by corwinharrell** [comment]
yep this should also be straightforward for design as well. Happy to tackle this in the next sprint.

**Comment by jimmy3dita** [comment]
> Awesome, I will include this improvement in the next sprint - as the red packets are flowing now and it seems to me a missed opportunity.

Thank you! Feel free to pull it on "design" and assign it to yourself as soon as you start working on it 🙏

**Comment by corwinharrell** [comment]
@jimmy3dita @Patrick1904 What's the best way for me to get a neardrop in order to capture the current flow for funding a new account via neardrop?

**Comment by Patrick1904** [comment]
> @jimmy3dita @Patrick1904 What's the best way for me to get a neardrop in order to capture the current flow for funding a new account via neardrop?

@corwinharrell you can create a testnet near drop here: https://near-drop-testnet.onrender.com/

**Comment by Patrick1904** [comment]
@corwinharrell some notes/recommendations after I started prototyping this:
1. I added separate linkdrop 'landing page' (`/linkdrop/contract/key`) that shows the linkdrop value and gives the user option to claim to current account or create a new account (which sends to `/create`). Just minimal for functionality and not recommending this actual design.
<img width="787" alt="Screen Shot 2021-03-15 at 6 31 12 PM" src="https://user-images.githubusercontent.com/24921205/111242630-ca575900-85bc-11eb-9992-54c4e0719f8f.png">

2. Since existing link drop generating apps already create links with `/create` vs `/linkdrop` we need to give logged in users an option to claim a linkdrop to their account if they land directly on `/create/contract/key`. We can redirect those users to `/linkdrop` route if they're logged in, however, it takes a short time to check if the user is actually logged in, so to avoid page flash we either need a full cover loading screen (or hide page content) while we're checking that, or we can skip redirect and place a button somewhere on `/create/contract/key` that says 'claim xx' that shows once the current account has loaded.
3. A different option would be to skip a separate 'linkdrop landing page' all together and instead add some type of banner/extra info to the `/create` page if user comes with linkdrop in the URL.

**Comment by corwinharrell** [comment]
@Patrick1904 I think the separate page for this makes sense, but I'd like to propose that we add a couple conditional paths to this to enable the optimum experience:

If the user is logged out, they may:

1. Create a New account with which to receive the NEAR drop (regular /create flow with receipt of NEAR once complete)
2. "Log in and Claim", which routes the user to /recover-account if the user is not already logged in. Once recovered, they would automatically receive the NEAR drop deposit.

In both scenario's above, we can display a message once logged in confirming the receipt of the NEAR drop.

If the user is already logged in:

3. Allow them to select the account that they want to receive the NEAR drop funds. Once they claim, they'd be redirected to the dashboard and shown the same receipt confirmation message.

[Figma for this is here.](https://www.figma.com/file/4ys8RNp9NG7vdZ2bDArCK9/Claim-NEAR-drop?node-id=0%3A1)

<img width="1414" alt="Screen Shot 2021-04-16 at 12 17 55 PM" src="https://user-images.githubusercontent.com/5934188/115054141-e39a4080-9ead-11eb-9aca-9e7a1c97ce76.png">

**Comment by jimmy3dita** [comment]
Let me know when I can test it!
I would put some "pressure" on the flow, as I would represent a user logging in with a Ledger, using a non-standard path, and an implicit account.

**Comment by Patrick1904** [comment]
> @Patrick1904 I think the separate page for this makes sense, but I'd like to propose that we add a couple conditional paths to this to enable the optimum experience:
> 
> If the user is logged out, they may:
> 
> 1. Create a New account with which to receive the NEAR drop (regular /create flow with receipt of NEAR once complete)
> 2. "Log in and Claim", which routes the user to /recover-account if the user is not already logged in. Once recovered, they would automatically receive the NEAR drop deposit.
> 
> In both scenario's above, we can display a message once logged in confirming the receipt of the NEAR drop.
> 
> If the user is already logged in:
> 
> 1. Allow them to select the account that they want to receive the NEAR drop funds. Once they claim, they'd be redirected to the dashboard and shown the same receipt confirmation message.
> 
> [Figma for this is here.](https://www.figma.com/file/4ys8RNp9NG7vdZ2bDArCK9/Claim-NEAR-drop?node-id=0%3A1)
> 
> <img alt="Screen Shot 2021-04-16 at 12 17 55 PM" width="1414" src="https://user-images.githubusercontent.com/5934188/115054141-e39a4080-9ead-11eb-9aca-9e7a1c97ce76.png">

Looks good to me! @corwinharrell @jimmy3dita I'll be picking this up next.

**Comment by vgrichina** [comment]
@corwinharrell design looks good overall, I only have some few small concerns:
- popups like "Your NEAR drop has been claimed" have historically been pretty glitchy (scroll issues, etc) when implemented on mobile. Let's make sure it's all clean in this case.
- I wonder if it makes sense to split instructions to go with their corresponding buttons
- wonder if "claim" is best word to describe what is happening. Maybe just "Receive on johndoe.near" and "Fund New Account"

don't have hard stance on anything except UI not being glitchy, just dumping my thoughts

**Comment by think-in-universe** [comment]
Some comments on its impact on airdrop procedure and security: 

1. The current airdrop procedure with tools like **redpacket** will re1direct users to the `/create/contract/key` route which will force the user to create new accounts. This is helpful when we're dropping only to really new users. I think this is still doable as long as we don't change the behavior of `/create/contract/key` route, and will use the route such as `/linkdrop/contract/key` for claiming NEAR drop into existing accounts.
2. Also, as Amos mentioned, allowing claiming NEAR drop into existing account is prone to be attacked by these who are able to steal the airdrop links from others via phishing, etc. The attacker could get the links and just stole all the funds into a single account, rather than have to create and manage an individual account for each airdrop link.

**Comment by think-in-universe** [comment]
> **Steps to reproduce**
> 
> 1. Create redpacket
> 2. Open it yourself
>    Observe that it requires you to create new account.

btw, just checked with @picturepan2   

In the latest version of [redpacket](https://redpacket.near.org/) released last weekend, now it already supports claiming the drop without creating a new account, if you login with an existing account. 

Is it still necessary to support this in wallet if it can be done at redpacket?

**Comment by corwinharrell** [comment]
> * popups like "Your NEAR drop has been claimed" have historically been pretty glitchy (scroll issues, etc) when implemented on mobile. Let's make sure it's all clean in this case.

@vgrichina yep totally valid. Just fyi @Patrick1904 and I added a prop to our modal component recently that allows them to be fullscreen on mobile, so they appear as full pages to mobile users, specifically to avoid any janky-ness that may be present when they are just a portion of the viewport height. Those instances will now be reserved for modals with very little content.

**Comment by Patrick1904** [comment]
@think-in-universe @corwinharrell @vgrichina I'm planning on redirecting any `/create/contract/key` URLs to `/linkdrop/contract/key`. If you don't want that behavior for redpacket links etc we could add support for `redirect=false` (`/create/contract/key?redirect=false`)

**Comment by crasskitty** [comment]
just out of curiosity, is there anyway we can do this retroactively as well 😅 ? I accidentally funded a wallet that had already been funded and don't have the original seedphrase for it anymore. I imagine I can't be the only person in the world with this issue.

**Comment by think-in-universe** [comment]
> If you don't want that behavior for redpacket links etc we could add support for `redirect=false` (`/create/contract/key?redirect=false`)

yeah. I think this will be helpful.

> In the latest version of [redpacket](https://redpacket.near.org/) released last weekend, now it already supports claiming the drop without creating a new account, if you login with an existing account.
> 
> Is it still necessary to include this feature in wallet if it can be done at redpacket?

and can we confirm this feature is still necessary in web wallet, after now redpacket's behavior has changed?

**Comment by Patrick1904** [comment]
@corwinharrell for the 'Login and Claim' case: The user could login with either seed phrase or Ledger directly, and we can claim the NEAR drop as the user is logging in. However, it seems that it might result in the wrong account getting the NEAR drop since the user can have many accounts on their Ledger, and in theory several accounts on their seed phrase too. We don't give much control in terms of recovering a specific account, especially while logging in with Ledger.

What do you think about re-directing the user back to the NEAR drop landing page once the user has recovered their account(s) vs claiming the NEAR drop automatically? That way the user has more control and can select whatever account they want to claim it to using the dropdown.

**Comment by corwinharrell** [comment]
@Patrick1904 yeah I'm happy with that and agree that feels like the ideal flow, so they can confirm the account that they wish to receive the drop 👍
