### ISSUE TITLE
Multiple HD Derivation path with Ledger

### ISSUE THREAD

**Issue by corwinharrell** [near/near-wallet#1536]
_For additional context and discussion, see the corresponding [Roadmap Issue](https://github.com/near/near-wallet-roadmap/issues/6)_

### Summary
As of today, wallet.near.org supports only a single derivation path, located at 44'/397'/0'/0'/1'. Therefore, NEAR webwallet supports only one account using Ledger Nano - even if the application on the Ledger device and near-cli are perfectly capable to generate and sign wallet pubkeys on any desired derivation path (44'/397'/0'/0'/n').

### Intended Outcome
As a power user, I want to leverage multiple pubkeys/derivation paths of my Ledger Nano wallet, such that I can manage more than one private key with the same physical device.

This new feature will help users who have more than one NEAR account, and will remove the need for near-cli on any pubkey that is different than 44'/397'/0'/0'/1'.

### How will it work?
While the backend and the API already support an arbitrary derivation path - such that one single Ledger Nano can manage multiple NEAR keys - the frontend is not yet able to manage them.
This feature will integrate the low-level derivation path selection in the user interface, enabling power users to manage multiple keys from the same device.

### Design Resources
**Figma:** https://www.figma.com/file/sxyMNqywLf2FfxRcjNEvdS/Ledger-HD-Path?node-id=0%3A1

**Comment by corwinharrell** [comment]
Design is complete. Proposing the following solution:

- Add a small `Advanced Options` component to the Ledger sign in screen
- The user can expand the options at which point they will see the current HD path (0 by default)
- The user may change the default path by altering the last digit with either mouse or keyboard input.
- Once the path has changed, the user must set the path.
- After setting a new path, the user may proceed with the sign in flow as they normally would. Subsequent screens would just show whatever accounts are being recovered via that path and will ask for approval on their ledger device for each account they wish to import.

![HD Path Selection](https://user-images.githubusercontent.com/5934188/111219389-5615b900-85ae-11eb-8388-e64960e52a10.gif)

cc @Patrick1904 @vgrichina @jimmy3dita

**Comment by jimmy3dita** [comment]
What happens specifically after I select a ledger path? It seems that near wallet signs transactions to authorize new public keys. I won't post here the txs for privacy reasons, but I'm wondering if other users (like me) might want to know better what is happening.
As a power user, a disclaimer like "private keys will stay on your Ledger" or "no additional keys will be added" might help to better understand what is being done

**Comment by Patrick1904** [comment]
I can see that @vgrichina has already added support for non-default paths in the ledger-app: https://github.com/near/near-ledger-js/blob/master/index.js#L19

Will start working on this next.

**Comment by corwinharrell** [comment]
@jimmy3dita happy to add an intermediary step or some additional messaging. I was using the multitasker tool as reference which I know if pretty rudimentary but doesn't have any actions occurring after selection.

**Comment by jimmy3dita** [comment]
@vgrichina wanted to use this thread to raise again the pubkey UX issue discussed on #1559 and previously on #772.

High level:
- is it possible to skip any authorization of the contract helper until the user must sign a transaction? 
- is it possible to "batch" in one transaction key authorization -> signature -> key removal?
- how this feature can be merged with https://github.com/near/near-wallet-roadmap/issues/10 ?

**Comment by eriktrautman** [comment]
I see this marked Released - GA but am not seeing the feature in the wallet. When setting up a new wallet account, it still asks for permission for the default path only:
![image](https://user-images.githubusercontent.com/2977438/127820390-455a50fe-ad6d-4ee8-9399-2975f225cf52.png)

**Comment by eriktrautman** [comment]
It'd be helpful to update the answer(s) to this post to reflect how this is done -- https://stackoverflow.com/questions/64562859/how-to-add-a-ledger-enabled-account-created-outside-of-near-wallet-to-the-near-w

**Comment by loupiote** [comment]
I posted this related post on reddit:

https://www.reddit.com/r/ledgerwallet/comments/13c5jwf/comment/jjjsfdi/?utm_source=share&utm_medium=web2x&context=3

here is the copy:

all right, i found this:

https://github.com/near/near-wallet/issues/1536

it says that:

wallet.near.org supports only a single derivation path located at 44'/397'/0'/0'/1'. Therefore, NEAR webwallet supports only one account using Ledger Nano - even if the application on the Ledger device and near-cli are perfectly capable to generate and sign wallet pubkeys on any desired derivation path (44'/397'/0'/0'/n').

So basically that explains why Ledger Live and [wallet.near.org](https://wallet.near.org/) generate different NEAR accounts, that's because Ledger Live uses m/44'/397'/0'/0'/0'  and [wallet.near.org](https://wallet.near.org/) uses m/44'/397'/0'/0'/1' .
This is very problematic, and it seems to me that the bug is in [wallet.near.org](https://wallet.near.org/) , as it should either allow the use to specify the derivation path they want to use, or use 44'/397'/0'/0'/0' rather than 44'/397'/0'/0'/1' .

But I think Ledger Live should use 44'/397'/0'/0'/1' for compatibility's sake. If LL is able to create multiple NEAR accounts (which I am not sure it can), then clearly only one of those accounts will be reachable with [wallet.near.org](https://wallet.near.org/) .
To make things even worst, some other wallets (e.g. Exodus) use 9000' instead of 397', it seams.
