### ISSUE TITLE
Wallet returns "User rejected" back to the app on failed transaction

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1608]
# Summary

When transaction fails for whatever reason:
  - wallet doesn't show a reason
  - app receives only `?errorCode=userRejected`, which is wrong and no information on transaction hash to lookup the error

# Context

Example of such transaction: https://explorer.testnet.near.org/transactions/DBH3nBX5Jorzp7R1nbssDriVg7GGoMdugxVLkbgbHFtQ

# Steps to reproduce

1. Open app
2. Call to sign transaction that will fail
3. Sign transaction in NEAR Wallet
4. Observer error, click "Close"
5. See that return url only contains `?errorCode=userRejected`

**Comment by jimmy3dita** [comment]
@ilblackdragon what is your expected behavior? This will help me understand if is a bug or an enhancement.

If the errorCode is wrong (should have been something different), it's a bug.
If the error should provide different information, is an enhancement with `Priority x` that requires a small design phase
