### ISSUE TITLE
Transfer Fungible Tokens - Version 0

### ISSUE THREAD

**Issue by stefanopepe** [near/near-wallet#1714]
## Feature recap
In an effort to make NEAR Wallet an asset management tool, this feature will enable users to send their fungible tokens directly from the wallet UI.

This is a blocking feature for our thriving DeFi ecosystem.

More info: [Fungible tokens: manage transactions](https://github.com/near/near-wallet-roadmap/issues/15)

## Story

As a wallet user who wants to send part of his `Fungible Tokens` balance, I want to `select the fungible token from the available list` and define the amount, so I can send the balance to other wallets.

## Acceptance Criteria

- [ ] The `/send-money` function allows the selection of one of the available fungible tokens
- [ ] This function allows the user to define the amount to send
- [ ] This function allows to send "max"
- [ ] This function won't send an amount higher than what is available
- [ ] This function won't list fungible tokens with zero balance
- [ ] This function would show the NEAR tokens needed for the gas
- [ ] The recipient dashboard shows an updated balance (upon refresh)
- [ ] Mobile ok
- [x] #1909

## Unhappy Path
- The user won't see an updated fungible token balance
- The user is not able to select a fungible token even if the balance is > 0
- The user runs out of NEAR tokens to pay for the gas, and the transaction fails
- The contract call fails for unexpected error at the RPC level, and the user is not informed

## Resources

- Figma Document: https://www.figma.com/file/unSbZpLnFv0oYBcU1gURWR/Transfer-Fungible-Tokens?node-id=304%3A593

## NOTES
This is related to epic #456 and [Fungible Tokens: display balance](https://github.com/near/near-wallet-roadmap/issues/14)

**Comment by jimmy3dita** [comment]
@corwinharrell please edit/add/remove any of the content above, it's still a draft

**Comment by Patrick1904** [comment]
@stefanopepe @vgrichina @MaximusHaximus: my understanding is that storage deposit is required for the receiver to be able to receive a FT. The sender could pay for storage deposit on behalf of the receiver before sending tokens, however, the tokens won't show up in the receivers wallet unless the storage deposit was paid for by the receiver (current indexer limitation?).

Is this something that we have to take into consideration when designing this? For example, do we need to add ability for users to manually 'add' FT to their wallet by initiating a storage deposit for a specific token?

**Comment by stefanopepe** [comment]
@Patrick1904 I'm not sure how to address your concern: we have to track this information from the indexer anyway, users are expecting to see tokens in their wallet (e.g. received via Bridge).

I see two possible ways to solve this one:
1. simply show every received token, and blend the storage costs with the first outgoing transaction. Essentially, the first tx will be more expensive (a batch transaction with the storage deposit + the call method to transfer the funds). When we have a very large landscape of tokens (and airdrops), we may want to add "favorites" and "hide" buttons next to every token.
2. introduce an "enable transfers" button, with a price tag - so the user doesn't risk paying the storage fees for useless airdropped tokens, and then run out of NEAR to pay for the good ones

This may need support by @corwinharrell UX work.

Is the issue blocked?

**Comment by Patrick1904** [comment]
@stefanopepe, AFAIU, we'll need to check if the receiver has a storage deposit for the specific token. If the receiver does not have a storage deposit, the sender will have to pay for the storage deposit, and then send the tokens (in order for the token to show up on the receivers wallet).

In terms of UX, we can do all this in the background, however, the main thing to consider is that the cost for storage will be an unexpected 'extra cost' for the sender.

@evgenykuzyakov - please correct me if my assumptions are incorrect.

**Comment by stefanopepe** [comment]
To make sure I understand correctly:
1. even if my account got plenty of near for the storage (e.g. 100), do I still have to sign a transaction for each of the received fungible tokens?
2. if I don't have enough tokens and the sender doesn't pay for the storage, the transaction is successful or not?
3. is this problem already present in the current wallet version, regardless of the token transfer problem?

**Comment by corwinharrell** [comment]
I'm blocked on design here until we have clarification on @stefanopepe's questions above.

Additional Questions:

- How is this currently handled by the bridge? ie if I complete a bridge transfer, AFAIK the token I just bridged will show up in my wallet. I'm not aware of storage costs being surfaced at any point in the process
- What is an example storage cost for a single token?

**Comment by stefanopepe** [comment]
From my conversation with @vgrichina yesterday:
1. no fungible tokens can be transferred to the wallet without paying the storage fee in advance - so the issue is informing the user that sending `nETH` to a wallet that never got them before will require an additional one-time fee to pay for the storage. I don't have a specific number available, but if it's higher than `.03` we should make the user aware of this
2. explained by 1: I will always need a NEAR balance to operate with fungible tokens. I can see that some accounts may be very long on Tether or DAI, and will keep a NEAR tokens balance to the minimum necessary for storage fees and gas.
3. no the problem is not present right now, as the cost of the operation is completely on the sender. In practical terms, the only way to send FTs to a wallet is via ref.finance >> which is charging an additional withdrawal fee every time a token is witdhrawn for the first time

+1 on knowing an example of storage costs per token. @Patrick1904 @vgrichina any ideas on where we can pull out this info?

**Comment by vgrichina** [comment]
> The sender could pay for storage deposit on behalf of the receiver before sending tokens, however, the tokens won't show up in the receivers wallet unless the storage deposit was paid for by the receiver (current indexer limitation?).
> 

@Patrick1904 this limitation is solved:
https://github.com/near/near-contract-helper/pull/422

**Comment by vgrichina** [comment]
My understanding of how transfer would work:
1) if receiver has storage deposit already – we just need to transfer tokens
2) if receiver doesn't have storage deposit, transaction should contain 2 actions (storage deposit and transfer).
3) receiver never has to pay for anything

My understanding is that we can use this API to determine how much is needed to attach for storage deposit:
https://web4.near.page/web4/contract/berryclub.ek.near/storage_balance_bounds

See relevant standard here:
https://github.com/near/NEPs/blob/master/specs/Standards/StorageManagement.md#reference-level-explanation

**Comment by vgrichina** [comment]
> 2. if receiver doesn't have storage deposit, transaction should contain 2 actions (storage deposit and transfer).

also looks like `storage_deposit` action has `registration_only` flag, that can be used to make sure we don't over pay for storage

**Comment by corwinharrell** [comment]
I'd like to request a list of available TXN metadata in order to consider how it might best fit into the wallet UI. The goal is to provide the user with more detailed metadata around their transaction both before and after they submit their transfer:

### Pre-submission
- Estimated Fees?
- Estimated Processing time?

### Post-submission
- Actual TXN cost?
- Explorer link to TXN?
- Actual processing time?

Not looking to discuss what we think _should_ be displayed atm, just looking to get a comprehensive understanding of what data is available to us. cc @stefanopepe @Patrick1904 @vgrichina

**Comment by Patrick1904** [comment]
**Estimated Fees?**

AFAIU the gas cost to send tokens should be negligible and same as sending $NEAR: https://docs.near.org/docs/concepts/gas#thinking-in-gas
<img width="759" alt="Screen Shot 2021-06-04 at 4 01 00 PM" src="https://user-images.githubusercontent.com/24921205/120870552-1081e000-c54e-11eb-82c8-8661e10a0351.png">

> My understanding is that we can use this API to determine how much is needed to attach for storage deposit:
> https://web4.near.page/web4/contract/berryclub.ek.near/storage_balance_bounds

However, the sender will have to pay for the storage deposit _if the receiver does not have storage deposit already_ (still pretty small) - which we can check before making the transfer. It's probably worth showing this extra cost to the sender on a confirmation step before confirming the transfer.

**Estimated Processing time?**
AFAIU should be as fast as sending $NEAR
**Actual TXN cost?**
Info is available
**Explorer link to TXN?**
Info is available
**Actual processing time?**
Should not be necessary

**Comment by stefanopepe** [comment]
@corwinharrell @Patrick1904 Is this one still blocked?

**Comment by corwinharrell** [comment]
@stefanopepe nope!

**Comment by corwinharrell** [comment]
Design Complete: https://www.figma.com/file/unSbZpLnFv0oYBcU1gURWR/Transfer-Fungible-Tokens?node-id=304%3A593

**Comment by Patrick1904** [comment]
@corwinharrell @stefanopepe,

@marcinbodnar @MaximusHaximus and myself just went over the design to plan the implementation of token transfers. We have some questions and concerned outlined below:

We believe that a **confirmation screen** (like our current send and stake flows) is warranted for the following reasons:
1. Since the user is selecting the `receiver` on the last step, the user may benefit from a 'read-only' step before confirming the action (like our current send and stake flows). It might for example happen that the user enters a slightly wrong Account ID, that's still valid, but not the intended Account ID, however, because of the screen check mark and lack of confirmation step, a user might miss that.
2. We want to be able to determine if the receiver will need a a _storage deposit_ as part of the send action. Making sure the user has finished selecting the `receiver`, not just that the user has entered a valid Account ID, will help make this accurate.
3. Currently our `/send` route supports an optional `amount` and `receiver` URL params. Having a confirmation step will allow the user to bookmark the page with the `amount`, `receiver`, and `token` in the URL and be sent directly to the confirmation step.
4. We can add 'edit' options to the confirmation screen for the `amount`, `receiver`, and `token` variables, to make it simple for the user to edit a variable before confirming the transfer (similar to staking UX).
5. Because the user can have multiple accounts, and it's easy to forget or miss which account is currently active, we believe that it would be beneficial to include the `sender` account on the confirmation screen.

Some additional UI needed:
1. Send/Receive buttons for mobile (I remember you were considering putting it in the nav dropdown).
2. Where do we put the 'buy' button that currently redirects to the `/buy` page

Some additional UX that we're wondering about:
1. If the user comes to the send flow with params for `amount`, `receiver`, and `token` populated, but one or more of the variables are invalid (for whatever reason), what UX are you envisioning for this scenario? Do you see the user being sent to the first step of the send flow, or are invalid variables highlighted on the confirmation screen, etc?

**Comment by Patrick1904** [comment]
Also @corwinharrell, after reviewing the above, how do you feel about aligning the desktop and mobile with an on-page UX, vs special modal UX for desktop? There are quite a few issues that we have to deal with (esp. routes/params) if we do a modal UX for desktop. We can always implement a modal UX for desktop afterwards if you think it would be better.

**Comment by corwinharrell** [comment]
@Patrick1904 thanks for the feedback. I'm not opposed to anything suggested here so will go ahead and make some tweaks to the designs today to accomodate. To answer a couple of your questions:

> Where do we put the 'buy' button that currently redirects to the /buy page

The send/receive/buy buttons will remain on the Wallet dashboard. The addition of the button in the header is simply to make it easier to access from elsewhere in the app. Nothing needs to changes here.

> If the user comes to the send flow with params for amount, receiver, and token populated, but one or more of the variables are invalid (for whatever reason), what UX are you envisioning for this scenario? 

If we are introducing a confirmation screen, I think the best option would be to take them here, with an additional message that says something like "your transaction contains invalid paramters, please fix the issues before confirming your transaction." and then allowing the user to go back and edit those parameters in the context of the normal flow.

**Comment by MaximusHaximus** [comment]
We shipped this!
