### ISSUE TITLE
TestNet wallet page is blank for users who have logged in

### ISSUE THREAD

**Issue by think-in-universe** [near/near-wallet#1799]
**Problem**
If you already have logged in testnet wallet before, after opening https://wallet.testnet.near.org/ or login an testnet app with wallet, you'll see a blank page and nothing is rendered.

![image](https://user-images.githubusercontent.com/46699230/120260060-b07a0800-c2c7-11eb-82fa-af530a15a94e.png)

If you clear the local storage, the page could be rendered successfully. You don't have to remove all the items in local storage, but at least one item with the key v4.***** (I forgot the actual name) and it will work well

**Expected Behavior**

The wallet should render correctly even if the user has logged in before. 

**Steps to reproduce**

1. You should have logged in testnet wallet before.
2. Open the latest version of testnet wallet: https://wallet.testnet.near.org/
3. The page is blank

**Comment by stefanopepe** [comment]
I wasn't able to reproduce the issue, even on different browsers.
@MaximusHaximus it seems to me that we are going to address localstorage issues with the new Redux persistent state, right?

**Comment by MaximusHaximus** [comment]
I reached out to a user that reported this issue via Discord, and they said it resolved itself, without any action from them (they didn't clear their localStorage), which indicates that this appears to be an intermittent low-level problem rather than a permanent issue with a key in localStorage, related to rendering the wallet when there are accounts loaded.  By removing localstorage keys, the case that caused the error was bypassed. Any time there is a blank screen, we can assume that a hard error was thrown somewhere inside of our rendering stack, which should print errors to the browser console -- those errors are going to be our best tool to try to identify what case is causing this error to be thrown -- anyone who experiences this issue should check the console and take screenshots of any error stack traces for us to investigate further, before doing anything to their localstorage -- this will let us narrow down the source of the problem.

**Comment by think-in-universe** [comment]
@MaximusHaximus thanks Daryl, yeah. this is great. 

better error log will make it easier for our developers to report and issue, and identify the root cause. :)

**Comment by stefanopepe** [comment]
@think-in-universe do you still have the issue, or we can close this one?

**Comment by think-in-universe** [comment]
@stefanopepe yes. I cannot reproduce the issue now. we can close it.
