### ISSUE TITLE
NEAR <> Fiat Conversion

### ISSUE THREAD

**Issue by corwinharrell** [near/near-wallet#1854]
## Problem
Users currently have no way to determine the fiat equivalent of the NEAR values displayed throughout the wallet. This means that in order to reason about balances, transfers, and fees in a way that is familiar to them, they must perform conversions manually on their own.

#### How did we discover this problem?
We've received feedback both internally and through our various community channels that wallet users would benefit from seeing values in both NEAR and the fiat equivalent.

#### Job Story(s)
- When viewing any NEAR value in the wallet, I want to see or have access to a fiat/USD conversion, so that I can reason about my balances and amounts in a way that is more familiar and confidence-inspiring.

#### What are we planning to do about it?
- We will be introducing a new conversion component to display across the application wherever there is a NEAR amount. The component will consist of two parts: a token value denominated in NEAR, and a fiat value denominated in USD.
- The component will need to fetch the conversion values from an API. At this point, the front-runner is Coinmarketcap.
- In some instances, the user should have access to a control that allows them to switch which value is visually emphasized.

#### What are we _not_ planning to do about it?
- The first iteration of the conversion component will be limited to USD. In the future, we may consider other fiat conversions or conversions against other tokens.

## Measuring Success
- We should closely monitor user feedback once this feature is released in order to determine its success. This feature is fairly standard in almost all blockchain wallets and applications, so it is ultimately a success for us to have "caught up" to the standard by implementing it.

## Resources
- [CoinMarketCap API](https://pro.coinmarketcap.com/)
- UX / UI: For designs see #1714

**Comment by corwinharrell** [comment]
cc @stefanopepe @Patrick1904 @marcinbodnar

**Comment by stefanopepe** [comment]
From my initial research, I think we can adopt Coingekko APIs: they have low-volume endpoints (50 queries per minute max that we can query ~once per minute) that in my opinion is more than enough for our needs.

**Comment by marcinbodnar** [comment]
I'm not sure if refreshing USD value automatically every few seconds is the best idea, the problem will be that the values will be constantly changing, and if for example, the user will be in Transfer flow he will see USD value change every few seconds. 

I think a better idea would be to add a refresh button:
 - one somewhere in the main menu
 - or everywhere where USD values will be shown
 - or for example, refreshes the USD value if a user clicks on USD value.

Thanks to that:
 - value will not be constantly changing
 - user will be able to see a more accurate USD, because it will be calculated on click, and the user doesn't have to wait till it refreshes, which might not be obvious when it will happen.

We can add automatic refresh in several situations only, but I'm not sure if it's necessary in all of them, for example:
 - user changes the route
 - browser window with Wallet is changed from inactive to active
 - on account import and create.

**Comment by corwinharrell** [comment]
I don't think we need to worry about a refresh button or triggering every few seconds. I think once per minute is plenty, and then each time the user changes routes or refreshes their browser window. @marcinbodnar any opposition to this?

**Comment by stefanopepe** [comment]
> I don't think we need to worry about a refresh button or triggering every few seconds. I think once per minute is plenty, and then each time the user changes routes or refreshes their browser window. @marcinbodnar any opposition to this?

I surprised myself reloading multiple times apps like Blockfolio like a slot machine, to see if numbers go up or down 😅

@marcinbodnar @MaximusHaximus is it reasonable to "proxy" this value on our backend, querying Coingekko once a minute, and then max every 2 seconds (to spare their APIs) if someone is calling the endpoint?

**Comment by MaximusHaximus** [comment]
> > I don't think we need to worry about a refresh button or triggering every few seconds. I think once per minute is plenty, and then each time the user changes routes or refreshes their browser window. @marcinbodnar any opposition to this?
> 
> I surprised myself reloading multiple times apps like Blockfolio like a slot machine, to see if numbers go up or down 😅
> 
> @marcinbodnar @MaximusHaximus is it reasonable to "proxy" this value on our backend, querying Coingekko once a minute, and then max every 2 seconds (to spare their APIs) if someone is calling the endpoint?

Absolutely -- we will need to make the request for the USD values go through the contract helper, which can maintain a cache of the value so that we only re-fetch the value once every couple of seconds, that way increased user load on the frontend will not cause us to exceed the quota of Coingekko API calls per minute. :+1:

Like @corwinharrell , I don't think that having the value be stale on the browser by a few seconds is an issue at all.  It's critical to understand that even Coingekko doesn't provide any guarantees that the number we get from their API is close to real-time accurate, so we're going to need a disclaimer for users of the wallet _anyway_ telling them that this is an estimate that may be out of date.

We _could_ show the last timestamp that we loaded the value from Coingekko to show the user how far out of date it is, but i'm not a fan of that because even _that_ could be misleading since the value from Coingekko itself may be out-of-date.
