### ISSUE TITLE
Navigation bar disappears

### ISSUE THREAD

**Issue by ihaid** [near/near-wallet#1887]
**Problem**
Navigation bar disappears when switching account 

**Steps to reproduce**

1. Log in to 2 accounts
2. Go to "Import Account"
3. Click "Sign in with Ledger"
4. Switch between your accounts
![image](https://user-images.githubusercontent.com/38665104/124646416-4859ab80-de9d-11eb-913a-d77619aad9b9.png)
![image](https://user-images.githubusercontent.com/38665104/124646448-53acd700-de9d-11eb-8a7d-3487c47fed89.png)

**Comment by stefanopepe** [comment]
I wasn't able to reproduce the issue. Can you submit a video with the steps you are following? I'm not sure I'm doing the steps correctly

**Comment by ihaid** [comment]
https://user-images.githubusercontent.com/38665104/125656150-3ff19605-634a-4055-904a-449df81dd408.mov

@stefanopepe

**Comment by stefanopepe** [comment]
Interesting.

assigning to @MaximusHaximus & cc @Patrick1904 to investigate the glitch

**Comment by Patrick1904** [comment]
@marcinbodnar thinking this might be related to `flowLimitation` - do you know if there's a quick fix?

**Comment by marcinbodnar** [comment]
@Patrick1904 It's probably a quick fix, but nothing comes to my mind, need to investigate it.

**Comment by marcinbodnar** [comment]
@Patrick1904 Fix ready here #1968

**Comment by marcinbodnar** [comment]
@MaximusHaximus we should also check other situations like that, that might appear. Added an issue here #1970

Also regarding routes, some time ago I had an idea to add all of our routes in one object #678, additionally, we can use it in `Routes.js` to map routes object, instead of writing all routes inline. The idea appears when we had a bit simpler routes but I think it still can be implemented.
