### ISSUE TITLE
Coin-op rel.2: multisig 

### ISSUE THREAD

**Issue by stefanopepe** [near/near-wallet#2012]
## Context
Today NEAR Wallet provides a very small amount of tokens, `0.02`, to cover the named account gas fees needed during the onboarding.
Some users are exploiting this feature to create bogus accounts, extracting this small value without the real intention to use the account.
The solution is to introduce a temporary lock to these `0.02` tokens, and an automated transaction that returns them to the coin-op service as soon as the wallet receives funding and is able to sign the first transaction.

## Story

As a Wallet Manager who needs to maintain the coin-op in the long term, I want to automatically recover the `0.02` tokens so I can re-use them for new users joining in the future.
As a new Wallet user, I want to choose the name of my account and complete the onboarding process as much as it is today.

## Acceptance Criteria

- [ ] On new account creation, the wallet deploys our existing multisig contract (as it's used for 2FA)
- [ ] This multisig contract is configured to lock the transfer of the `0.02` tokens until `>0.2` funds are deposited
- [ ] The multisig is removed as soon as the user adds the requested `0.2` tokens
- [ ] The wallet, as soon as the funding is complete, signs a transaction to remove the multisig and return the `0.02` tokens back to the coin-op service
- [ ] Until the account received `0.2` tokens, the wallet is only able to authorize login and key management
- [ ] Doesn't block the partner login button > account creation > redirect virtuous path
- [ ] Compatible with our airdrop claiming process
- [ ] Doesn't run out of storage/gas with most used ecosystem apps (Ref, Paras, Mintbase, Pulse, Aurora)

## Unhappy Path
- The account runs out of gas, crashing this process "mid-flight"

## NOTES

- Needs ack of the concept by @ilblackdragon and @MaximusHaximus

**Comment by stefanopepe** [comment]
Opportunity vs Risk:
O: we can provide more funds to each account, to cover higher gas costs (e.g. Ethereum Bridge)
O: we can do micro-monetization of the service >> get back `0.03` for a whopping 50% interest on this micro-lending
R: this is introducing additional complexity during the onboarding, a glitch and we've lost the user
R: this is not resolving name-squatting attacks

**Comment by think-in-universe** [comment]
The workflow makes sense, though it looks a bit complex (the new users might be confused about the transaction history from explorer, since a contract was deployed.)

A few questions: 

1. Will `lock the transfer of the 0.02 tokens` work as expected with multisig contract? Will we deploy [this one](https://github.com/near/core-contracts/blob/master/multisig/src/lib.rs), or do we have a specific version designed for the workflow?
2. Is `Until the account received 0.2 tokens, the wallet is only able to authorize login and key management` still necessary under the current model? If we could lock the transfer of the `0.02N`
3. What's the extra cost to cover the storage of the `multisig` contract cost more storage? How much extra cost will we pay initially? Just to check, although we'll finally remove the contract from the account.

**Comment by nearmax** [comment]
I suggest before we implement this solution to do the following:
* Collect feedback from the community and partners to know whether they are okay with the change;
* Sync with Developer Platform, Developer Relations, and Node Interfaces to make sure we are not adding a lot of work to them, because they would need to modify near-cli, explorer, and documentation to work with transactions that are proxied with the contract. Today, documentation and near-cli do not provide guidance on sending transactions through 2FA contract. Explorer might need to special case displaying these transactions;
* Decide what we do with the FullAccess key that we still keep even when 2FA is added to the contract (I just created a new account, added 2FA and verified that account still has a FullAccess key). We need to make sure our partners are not relying on this FullAccess key to work;
* Consider usual web2 alternatives, like banning IPs (I am not sure people can use VPN to connect from a large number of accounts a day), making verification more challenging, etc.

**Comment by stefanopepe** [comment]
@nearmax thank you for your feedback, I can see the issue from an ecosystem standpoint. Overall the issue is financial (the wallet wouldn't be sustainable in the long term) and in the product itself, since spamming users generate noise in the metrics and the network usage.

We'll keep the coin-op disabled by now, having NEAR Wallet how it worked until two months ago (which wasn't too bad anyway) at least until we release a "web2 solution" which at this point seems the only viable one without having to review how the 2FA was initially developed.

**Comment by stefanopepe** [comment]
Closing this one, as it didn't get an ack
