### ISSUE TITLE
Support Generic Signing of Data from User Chosen Accounts Without Login / Adding Key

### ISSUE THREAD

**Issue by mattlockyer** [near/near-wallet#2047]
## Problem
Currently, if you want a user to sign some data with any keys on their account they will need to first sign into your app. This flow can be a UX interruption and cost GAS, if all the app wants to know is which NEAR account you want to prove that you own.

#### How did we discover this problem?
Several partners have asked for this since... I want to say 6mo - 1yr.

#### Job Story(s)
- User is in app, has **not** signed in, app does not know if they even have a NEAR wallet
- App redirects to route in wallet e.g. `wallet.com/sign-message/[URI_ENCODED_MESSAGE]`
- Wallet shows the same route as signing for a TX e.g. **select account, click accept**
- User is redirected to app with **signature in query params**

#### What are we planning to do about it?
- Implement it

#### What are we _not_ planning to do about it?
- NA

## Measuring Success
- Apps can identify users without adding keys to their account (gas cost)

## Resources
- NA

**Comment by stefanopepe** [comment]
Followup to this request:
- we already have similar functionality buried in the wallet helper codebase, but it's undocumented
- V0 is pinned for the next sprint (Monday cc @MaximusHaximus )
- it needs minimum UI review, essentially to specify the difference from an on-chain transaction (cc @corwinharrell and @Patrick1904 )

Some corrections to the card above:

## Scope

#### What are we planning to do about it?
- Release a V0 with an endpoint/route within the wallet and a confirmation panel
- In the future, this should become part of `near-api-js` and not the wallet only

#### What are we not planning to do about it (for V0)?
- Build an end-to-end developer-friendly feature with code examples, documentation and e2e tests (at least for V0)
- Submit a PR to `near-api-js`

**Comment by starpause** [comment]
@stefanopepe is there any chance of getting the most fundamental documentation available before sprint end? Specifically Collab.Land is looking for this to allow for existing NEAR wallets to associate with their bot before the near.org/metabuidl (aug27).

**Comment by stefanopepe** [comment]
@starpause what's the volume and the impact of not having it? Is it blocking the August 27 event? Is it more valuable than having `coin-op.near` back and working as before?

Unfortunately, we have some long-awaited OOO time for one of the team members (planned way before knowing the strict urgency of this issue) and the remaining resources can be exclusively allocated to coin-op or this one, at least this week.

Realistically, given also the interruptions suffered during the weekend, this feature may anyway go live in the sprint after this one, and the spec made available later next week.

**Comment by ilblackdragon** [comment]
Just to link Ethereum's standards for this:
 - old one: https://eips.ethereum.org/EIPS/eip-191
 - new one: https://eips.ethereum.org/EIPS/eip-712

It's important to guard against arbitrary data signatures, because malicious code can get user to sign a transaction that user doesn't want to sign this way.

**Comment by starpause** [comment]
@stefanopepe it's hard to measure the impact of this because there isn't a 1:1 mapping of "if this is fixed we attract X users". By rough napkin math, it feels an order of magnitude more significant than coin-op. There are several communities of 80k+ members on the brink of joining NEAR if CollabLand bot is ready to go. Most of our new user spikes are from event activations where we can deploy linkdrops in the absence of coin-op. Resolution on this would have us on track to blow community squad OKRs out of the water 🙏😉

**Comment by MaximusHaximus** [comment]
We've come up with an approach to implement this capability in a timely manner and without adding new security risk vectors to the wallet such as signing transactions that could then be submitted on chain by the verifying app for malicious purposes.  The approach follows similar patterns as some existing functionality in the wallet surrounding Ledger usage.

## Goals
1. App authors should be able to verify account ownership without an actual on-chain transaction being submitted per verification, since on-chain transactions carry associated gas costs.
2. A new access key should not need to be created for each app that wishes to verify account ownership, or for every instance that account ownership is verified.
- We can use _the same key_ for every account verification done on a given device, rather than the current requirement to create a new function call access key for every app making the signing request.
3. Account verification should not introduce opportunities for malicious requests to compromise the signing account's security.
- We can use restricted access keys that are specifically configured in such a way that they cannot be abused; even if a payload is provided that would otherwise be concerning if executed on-chain, it will not be valid due to the configuration of the access key used to sign it.

## Resolution
1.  We will avoid the requirement to perform an on-chain transaction for every app who requests verification, or for every verification done by having the user sign a string that is provided by the app author with a key that the app author can find the public key for on-chain, and returning the signed value (or hash of that value?) back to the app author.
2. We will avoid creating new access keys per app or per instance of verification by using the same access key for all requests of  this type per machine the user is logged in on. This eliminates the requirement to have a new access key created each time an app author wants the user to verify their ownership of an account or for each app author who does so.
3. We will avoid replay attacks by ensuring that we always sign any provided strings using a restricted access key that is only allowed to call a _nonexistent function on the owners account_.

## Access Key Details
The access key that is created will be a functionCall access key.
It will have `methodNames` set to a single method name, `__wallet__verify_owner` -- a method that will not exist on the user's account.
As a result, anything signed by this key will not execute on-chain, ensuring we are not opening our users up to risk of signing messages that are actually valid on-chain transactions.
_This is an extension of a pattern already present elsewhere in the wallet_; we _already_ add a similarly designed key to ledger-enabled accounts to allow us to verify account ownership for `near-contract-helper` routes that should only work for the account owner (that key is named `__wallet__metadata`).

## Integration Interface
- New Route: `/verify-owner/[URI_ENCODED_MESSAGE]`
The **first** time that a user uses this route on a particular machine, they will be prompted to sign a transaction to create a new _limited access_ key on their account (or we could do it implicitly). Once the user has added the key to their account, they will be redirected to the `/verify-owner` route so they can seamlessly verify their ownership to the requesting app.  Similar to existing 'import account' flow, subsequent visits to this route on the same machine will not require signing a transaction to add a new key.

The `/verify-owner` screen will _only_ prompt the user to click a button to verify their ownership of their account, and inform them that no on-chain transaction will be performed to complete the operation; no on-chain transaction will be submitted.

When the user clicks the 'Verify I own the account' button, the wallet will sign the string provided by the app using the `__wallet__verify_owner` key and redirect back to the app with 3 pieces of data in the URL:
1. The signed data from the app (or a hash of the signed data?)
2. The account id the user used to sign the data with (since they can choose any loaded account in the wallet)
3. The public key of the key used to sign the data

The app can then verify the signature of the data matches with the public key on-chain, and verify that the account id provided owns that key (and even that it has the correct `methodNames` permissions?)

cc: @ilblackdragon @stefanopepe

**Comment by vgrichina** [comment]
> We can use restricted access keys that are specifically configured in such a way that they cannot be abused; even if a payload is provided that would otherwise be concerning if executed on-chain, it will not be valid due to the configuration of the access key used to sign it.

IMO it's much better to restrict payload vs add extra key. In fact we should at some point change Ledger implementation to avoid adding extra key (see https://github.com/near/near-wallet/issues/1899)

I think also given that we are certifying to external app, that yeah, this is a real user – we should prove ability to sign with full access keys (or sign with multiple keys for multisig). We know that say key metadata in contract helper is relatively low value data, but third-party apps can decide to protect more valuable stuff by wallet login.

We also need to figure out solution to https://github.com/near/near-wallet/issues/726. I was thinking to allow both `/login` and `/sign` to pass `signOnly` option (https://github.com/near/NEPs/pull/10/commits/d1cfcfbde967bc56687aa2f19f3128fb7532f16c) and then actually require this option at some point (so that every transaction signed by wallet is also validated by app).
Otherwise it's relatively easy to get tricked into signing and sending transaction after clicking a phishing link.

Proposed solution is potentially smaller in scope (no extra keys needed) and solves both issue of authorising the app and minimising phishing possibilities.

> We will avoid replay attacks by ensuring that we always sign any provided strings using a restricted access key that is only allowed to call a nonexistent function on the owners account.

Generally replay attacks are avoided on NEAR because you have to supply recent enough `blockHash` for transaction. However it's true that we shouldn't allow to sign arbitrary data, enforcing specific fake method / contract is good idea.  Having separate access key is probably overkill,  though I'd leave it to @abacabadabacaba to comment more on security aspects.

**Comment by mattlockyer** [comment]
I second the approach of restricting payload for now to get this done faster and still remain safe. I think it is incumbent on us to come up with a solution to prove account ownership without adding keys.

Case: I'm dropping a lot of extremely low value accounts soon. These accounts will barely have enough gas to add a key if at all. But I still want to create apps that allow them to redirect to NEAR Wallet and prove who they are to my app. AFAIK every partner simply wants to prove ownership without adding keys.

If login is all we're really trying to prove, why not restrict what the wallet will sign on this route to simply anything matching **blockNumber** or **accountId of app + blockNumber**?

near-contract-helper already uses this pattern and it comes from the wallet: https://github.com/near/near-wallet/blob/574bc8710f01d6a32c60e9c9bfbefc43950aa859/packages/frontend/src/utils/wallet.js#L729-L744

I would be fine with this and we can revisit if apps want to do more complicated things later e.g. metatransactions. 

@MaximusHaximus should I update the issue to reflect a smaller scope?

**Comment by stefanopepe** [comment]
I want to share some notes from my conversation @MaximusHaximus to move this work ahead, as we may have found a way to get the same result as Ethereum, "The NEAR Way".

At a high level, we would sign an invalid transaction with a valid signature.
This transaction would:
1. use an invalid method
2. use in the payload a block hash that is `t-x`, such that it's obsolete for the network
3. use in the method field the hash of the proof that we want to sign

Still work in progress, as:
1. the method should be a very long 32 bytes hex hash (or 64 char string)
2. the signer doesn't know the current block height/hash, so it's up to the application layer (and the user) to check if the hash is old enough

Anyway, this method is compatible with the limited access key idea with a small allowance

**Comment by mattlockyer** [comment]
Not sure I follow this exactly... but I guess this would allow applications to send arbitrary data to be signed?

If I understand correctly:
1. hash payload
2. put hash of payload inside invalid TX e.g. functionCall(receiver_id: 'some_impossible_account', args: [HASH_OF_PAYLOAD]) ???
3. then sign this TX but with block hash t - some x far from current finality
4. return to app

Seems like with 2 we don't need 3, but with both you're 100% certain nothing could happen with the user's account.

**Comment by vans163** [comment]
> I want to share some notes from my conversation with @MaximusHaximus to move this work ahead, as we may have found a way to get the same result as Ethereum, "The NEAR Way".
> 
> At a high level, we would sign an invalid transaction with a valid signature.
> This transaction would:
> 
> 1. use an invalid method
> 2. use in the payload a block hash that is `t-x`, such that it's obsolete for the network
> 3. use in the method field the hash of the proof that we want to sign
> 
> Still work in progress, as:
> 
> 1. the method should be a very long 32 bytes hex hash (or 64 char string)
> 2. the signer doesn't know the current block height/hash, so it's up to the application layer (and the user) to check if the hash is old enough
> 
> Anyway, this method is compatible with the limited access key idea with a small allowance

I dont get it, isnt the only thing this PR is asking is to be able to do 
```
return signature = nacl.sign.detached(message, secret_key)
```
but with the `secret_key` being stored on the wallet.near.org domain?

With the attack vector being a user can sign a (malicious) crafted transaction, but the user will be displayed by the wallet.near.org what data they are signing.

**Comment by mattlockyer** [comment]
On the surface it seems like overkill until you work on the wallet team and realize users don't read.

Combine that with fishing sites and you have a problem...

**Comment by vans163** [comment]
> On the surface it seems like overkill until you work on the wallet team and realize users don't read.
> 
> Combine that with fishing sites and you have a problem...

The solution is definitely a sound one, just maybe there is a simpler way, because this would require the backend verifying the signature to ship borsch deserializer + a base58 decoder. Not all languages support borsch. Example web platform  using PHP still that wants to have a login_signature/proof from a NEAR wallet.

**Comment by vgrichina** [comment]
> On the surface it seems like overkill until you work on the wallet team and realize users don't read.
> 
> Combine that with fishing sites and you have a problem...

@mattlockyer  I think the only new potential problem here is if you allow to sign completely arbitrary data (including valid transactions) but do not display it  as a transaction. 

If user has to approve transaction being signed, then there is not much difference in phishing opportunities compared to current `/sign` payload. 

However I agree with you 100% that users don't read. We should improve `/sign` route to make it more clear what is happening. For example I think we should keep track of which website you use with a given contract. So say if you haven't ever used `berryclub.ek.near` contract and are approving access to it for `berryclub.io` – it's all chill. But if you already used it before but landed on scammy `beryclub.io` – wallet should require extra confirmation from user that they know the potential consequences.

I'm also trying to build a way for every contract to provide default UI tied to the same NEAR account (https://web4.near.page), if it becomes common – maybe approving non-default UI should generally be a big deal.

**Comment by stefanopepe** [comment]
Short update, @abacabadabacaba is busy now, will be reviewing this proposal later this week. In the meantime we are working on the UX/UI and any other aspects that are not blocked

**Comment by almal** [comment]
Would be nice to finally to get "yes" or "no" on this feature.
Several web2<>web3 projects have been on hold for few month already.
Thank you!

**Comment by stefanopepe** [comment]
We plan to have it as "alpha". We have some work to finish this sprint, but I can see it being working on quite soon. Will let @MaximusHaximus provide more information around it.

**Comment by agileurbanite** [comment]
@MaximusHaximus can I get more details on why this is blocked?  Is this a capacity issue or dependency issue?

**Comment by agileurbanite** [comment]
Looking to get this prioritized

**Comment by dillchen** [comment]
chiming in here from @hicommonwealth/commonwwealth that this would drastically improve user experience
