### ISSUE TITLE
NFT doesn't show up when initially minted.

### ISSUE THREAD

**Issue by june07** [near/near-wallet#2226]
Similar or the same as this issue...
The wallet not displays NTF owned by the account #1836

Seems newly minted NFT's should show up under the minted account owners wallet... but they do not.  I had to transfer the NFT first before it would show up in the 2nd owner's (1st besides minter) wallet.

**Steps to reproduce**

1. Mint an NFT
2. Check the minter's wallet's collections tab (missing NFT)

**Comment by willemneal** [comment]
How was the NFT minted?  Currently the only way they showed up was after a transfer since there was no standard, however, now there is now a log event for minting, burning, and transfers: https://github.com/near/NEPs/blob/master/specs/Standards/NonFungibleToken/Event.md

I am not sure but I assume that after the indexer adds support for catching these logs, the wallet should have it too!

**Comment by june07** [comment]
@willemneal Hey thanks for the feedback.  Digging deeper into things, what you say is in line with my findings.  In trying to implement the Event interface in my NFT contract, I'm not sure I'm going down the right path.  From what I can tell, the current nft_transfer method which IS picked up by the indexer doesn't seem to "emit" any event... outside of what is happening on the blockchain.  So... is it safe to assume that what needs to change to have this work is on the Indexer side or some other part of the machine OUTSIDE of the scope of my NFT contract?  Or should I be implementing some EVENT in rust?

Still a bit unsure...

**Comment by june07** [comment]
So an update...

My attempt at following the spec https://github.com/near/NEPs/blob/master/specs/Standards/NonFungibleToken/Event.md and outputting the event data via logging, it seems that the wallet does not pick up the NFT in the original owners wallet.  

Even trying to "spoof" the event log (2nd image) by using the NftTransferLog interfaces doesn't work so that makes me think logging the events as I am isn't what is required...?

![image](https://user-images.githubusercontent.com/11353590/140389927-1bd73873-1150-4acf-81c4-55e28b9db2bb.png)

![image](https://user-images.githubusercontent.com/11353590/140389528-919d0d30-a247-409b-9677-47ef99812647.png)

**Comment by willemneal** [comment]
@june07 It looks like you correctly implemented the logs.  FYI I added a PR to the sdk to handle creating the logs, but it's still a WIP: https://github.com/near/near-sdk-rs/pull/627.  I noticed your `memo: null` and with my code the field will be ignored..

My guess is that the logging is still not implemented.  So for now one method is to first mint with the contract as the owner.  Then call's `ft_transfer`, in `ft_transfer`, check if it is private call `env::current_account_id() == env::predecessor_account_id()`, then use the unguarded internal transfer.  It's certainly not the best, but can be removed once the wallet using the events and upgrade without worrying about updating the state.

**Comment by stefanopepe** [comment]
Hey @willemneal @june07 thank you for pulling this up.
How are the storage fees taken care of?

**Comment by willemneal** [comment]
@stefanopepe Here is a PR I have that address refunding after multiple mints, but it also demonstrates how refunds are handled: https://github.com/near/near-sdk-rs/pull/618/files

**Comment by stefanopepe** [comment]
So, we can exclude that the problem is not having the NFTs stored/associated to the account state as it happens with other NFTs?
Other questions:
- Are there any key differences from how Paras or Mintbase store this info?
- How this information is presented by the indexer?

**Comment by willemneal** [comment]
Yes. The issue was that minting was not being captured by the indexer.  But transfer calls were.  So it's not the issue that the wallet's use of indexer wasn't finding NFT's because they weren't stored correctly.  Rather that it didn't know to associate an account with an NFT contract.  For example, previously I minted several times and nothing showed up.  But a single transfer from the same account meant that there was association and the remaining ones showed up.

The indexer team has finished the work to look for events and I verified with their public postgres endpoint that my event logs were being captured.  See this PR: https://github.com/near/near-indexer-for-explorer/pull/169

**Comment by stefanopepe** [comment]
So, to make sure I got it right, now the indexer is able to find the minted NFTs and the only missing piece is having the wallet perform these additional queries to it, to populate the collectibles pane in the dashboard.

As soon as you confirm, I'll ask @MaximusHaximus to look into it and scope down the work. Actually, you are more than welcome to participate in the PR

**Comment by willemneal** [comment]
You got it!  I'd happy to help push this through!

**Comment by willemneal** [comment]
Added the fix here: 

https://github.com/near/near-contract-helper/pull/532

**Comment by june07** [comment]
@willemneal Just wanted to say thanks.  It seems to be working splendidly now!  🍻
