### ISSUE TITLE
2FA email link key

### ISSUE THREAD

**Issue by hanakannzashi** [near/near-wallet#2324]
**Problem**
When a user set email link after enable 2FA ,the allowance of function-access-key of email link is 0.25N, not null. If user disable his seed phrase, the email link will be the only recover way, but it can be invalid due to allowance, then user cant recover his account

**Expected Behavior**
the allowance of  function-access-key of email link is null

**Steps to reproduce**
1. Ensure the email link and 2FA are disabled
2. enable 2FA
3. enable email link
4. find key detail of email link on near-cli

**Comment by stefanopepe** [comment]
Users are not supposed to disable the seed passphrase recovery when using 2FA, the UI should prevent that unless thre' already another recovery method enabled (email). 
Once 2FA is enabled, the seed must remain in place for two reasons:
1. the seed passphrase (as the email recovery link) is still needed to import the account on a new browser
2. there's no recovery passphrase for the 2FA private key, as the account recovery is handled by the seedphrase above

This issue needs a properly formed expected behavior from the side of the problem, instead of the solution: what is the user trying to do, that is not possible with the current 2FA configuration?

Happy to discuss the possible solutions after we understand the problem

**Comment by hanakannzashi** [comment]
@stefanopepe 
You misunderstood what I said. I mean set up a new email link AFTER enable 2FA, then disable phrase.In this way, there is only one way to recover the account, it is email.But the key of email -- its allowance is 0.25N, it means email will be invalid one day.

**Comment by hanakannzashi** [comment]
did you fix this problem? @stefanopepe
