### ISSUE TITLE
Use current account as funding method by default when creating a new account & re-use recovery key

### ISSUE THREAD

**Issue by Patrick1904** [near/near-wallet#2348]
Original issue: https://github.com/near/near-wallet/issues/2284

We implemented phase one of the implicit account onboarding in https://github.com/near/near-wallet/pull/2313. Phase two includes:
1. Using current account as funding method by default when creating a new account (while logged in)
2. Enabling users to re-use the same seed phrase / key when creating a new account, essentially making it possible for users to add the same key to multiple accounts.

Figma design: https://www.figma.com/file/yR4qz7oAjAiVAJ0hJSnQQj/Onboarding-Exploration?node-id=1%3A606

**Comment by Patrick1904** [comment]
@MaximusHaximus and @corwinharrell - the UI for this feature is done, but I know @MaximusHaximus has some concerns with shipping this 'shared seed phrases' feature, at least without any ability for users to manage multiple accounts with a single phrase outside of the initial setup flow. @corwinharrell any thoughts on this?

**Comment by corwinharrell** [comment]
I think it's a valid approach to hold off on the shared phrase stuff until we can also design and plan for better key management, so that a user has the following options:

1. See which accounts are secured by which keys
2. See which accounts share keys
3. Easily rotate keys, change keys, etc...
4. Have messaging around actions that ensure the user understands the implications of changes to keys
