### ISSUE TITLE
Select transaction `signerId` on wallet sign interface

### ISSUE THREAD

**Issue by esaminu** [near/near-wallet#2402]
## Story

As a dapp user, I want the correct signer account to be selected on the wallet sign interface so I can sign a transaction successfully.

Relates to: #2396 , #2399 

## Acceptance Criteria

- [ ] Given I navigate to `/sign` with a transaction(s) the account on the transaction's `signerId` should be selected
- [ ] Given there is more than one `signerId` in a transaction batch I should see an error
- [ ] Given the account on the transaction's `signerId` does not exist on the wallet I should see an error

## Resources

- [Figma Document](https://www.figma.com/file/9ImHeER6uE2i2oof41QCu6/signerId-Errors?node-id=2%3A2)

<img width="971" alt="Screen Shot 2022-01-26 at 9 06 17 AM" src="https://user-images.githubusercontent.com/5934188/151179186-7a0d9c51-a52b-46c6-a11c-c078bc38d7d3.png">

**Comment by corwinharrell** [comment]
Considering error states. My assumption is that to even _initiate_ a transaction, the user would need to be connected to the Ðapp via the wallet. Under this assumption, what is the event that a transaction's `signerId` might not exist in the wallet? Similarly, how might `signerId`s be mismatched?

Similarly,

**Comment by esaminu** [comment]
Requesting a transaction signature is an independent operation to signing in (requesting an access key). A Ðapp could send us a transaction to sign that has a `signerId` that is not logged in to the wallet. That would be the first error state in the story.

The second error state is quite edge case-y. It's when the list of transactions sent via the `transactions` url param does not have the same `signerId` for all transactions. After some thought and discussion I think we can remove explicit detection and handling for this case and simply display the error returned by rpc on any transaction that was incorrectly signed. I.e. we will always handle the batch of transactions using the `signerId` of the first transaction on the list.

**Comment by MaximusHaximus** [comment]
@corwinharrell

To clarify the /sign endpoint and its (lack of) relationship with the /login endpoint and the LAK that is created after a successful login transaction:

Signing in to a dapp is **not** a requirement for using of the wallet `/sign` API.

In fact, due to its very nature, because the /sign endpoint exists _specifically_ to support signing of payloads that use a FAK (thus has no `contractId` target), we can't even know if someone _is_ 'signed in' to a dapp that is relevant to the incoming transactions that are in the /sign request.

We could identify whether the user has a functionCall access key that targets the contract(s) that the transactions are being called against, but to do so we would need to parse the entire transactions payload and identify the target contract for every transaction.  Even then, we would only be guessing at this, and we would incorrectly think some transactions were not associated with 'logged in' contracts because many integrations submit transactions for _multiple_ contracts that are _not_ the same contract as the user gets a functionCall access key from a conventional sign-in.

ref.finance is an example of this, where interacting with the ref.finance UI may result in a set of transactions being sent to the `/sign` endpoint that interact with multiple (3+) different contracts, even though you only log in to a specific contract when logging into the ref.finance UI.

So while it's _typical_ for users to have the transactions that are sent to the /sign endpoint be composed from a context where they are 'logged in to a dapp', it's not a requirement.

The case for the user landing on the wallet using the `/sign` URL and not having the account that is the `signerId` of those transactions imported into the wallet is most likely to be a timing issue like the user clearing their wallet.near.org cache/localstorage in between logging in to the dapp and being redirected back to the wallet for a FAK signing request or the result of a lower-level integration with an app that doesn't use our standard dapp login flow  -- for example, apps that sign a user in without adding a LAK at all will be possible when we land signing of non-transaction data, since the dapp author will be able to verify that the user owns the account being used to log in _without creating a LAK at all_.

**Comment by corwinharrell** [comment]
Thanks for the clarification! Valuable context :)

In that case, I think @esaminu had it right in that we can display a take-over style error that prompts the user to import the missing account being referenced by the `signerId`. If the user was to Cancel, it would simply redirect them back to their previous context (most likely the dapp).

<img width="971" alt="Screen Shot 2022-01-26 at 9 06 17 AM" src="https://user-images.githubusercontent.com/5934188/151177590-4160f81b-a9c0-453a-89c3-2f66c7124035.png">

@esaminu Feel free to use the same component/pattern as the "Insufficient Network Fee" error that we recently implemented.

**Comment by corwinharrell** [comment]
Now, the second case that you mention here having to do with batch transactions is definitely more complicated. I think though that how we approach errors in that context has less to do specifically with `signerId` and more to do with how we handle batch transactions and their state. In the case of batch transactions, we need ways to indicate:

1. How many transactions are included in the batch (ie how many confirmations can a user expect to perform before they are "done")
2. Which ones have succeeded
3. Which ones have failed
4. Allow the user to see details of each and ensure that they have paths forward in any scenario, especially if a transaction in a batch fails before the entire batch is complete.

@MaximusHaximus My gut feeling is that we need to address this more macro problem on its own. Thoughts? Let me know if I'm missing the mark here as this is inherently complex.

**Comment by esaminu** [comment]
@corwinharrell Current behavior is that we send the transactions to rpc one by one in the batch and stop sending them and just display an error when we encounter one. The user has the ability to view the transactions they are sending in the "More Information" view:

<img width="1394" alt="Screen Shot 2022-01-26 at 10 24 04 PM" src="https://user-images.githubusercontent.com/5849204/151228821-d7475cf9-7919-4f3b-ae6f-fc023ca3fb03.png">

There are some issues around support for all types of actions here but I think the UI is informative enough aside from that.

**Comment by corwinharrell** [comment]
@esaminu ok feel free to adapt this for the scenarios that you are aware of and include me in a review and we can craft the copy per scenario if we need to.

**Comment by esaminu** [comment]
@corwinharrell @stefanopepe We have more information regarding the wallet's behavior wrt signing transactions and have come up with a proposed behavior in #2401. The current behavior and proposed PR are as follows:

#### Current Behavior

The wallet will deserialize the transactions in the url and **recreate** transactions with the `receiverId` and `actions` of the input transactions and the `signerId` of the account currently selected on the wallet. The wallet will then sign and send these transactions via rpc. 

When the user navigates to `/sign`, the wallet does not currently do any automatic account switching based on the incoming transaction(s) `signerId` **or** give the user the option to select a different account to sign and send the transaction with. This leaves the user stuck and is what has lead to the issues we've seen reported. The only way out is to change the active account on a separate wallet instance and then reattempt to sign the transaction.

####  Behavior on #2401 

In #2401 , we decided to do the following:

1. When the user navigates to `/sign`, we auto select the `signerId` of the first transaction if the user exists on the wallet. We currently do nothing if the account does not exist on the wallet, see discussion below.
2. We've added the account selector so that the user has further optionality and can send the transaction(s) with any of their available accounts. 

#### Discussion
The reasons to recreate the transaction from `receiverId` and `actions` as opposed to deserializing and sending as is are as follows:

- It is easier to communicate to the user that all of their transactions will be signed and sent with the selected active account.
- It's very difficult to communicate and manage multiple transactions signed by different accounts on the wallet's keystore, get approval for all of them and manage different error states.
- No matter the case, the transactions will _always_ be signed and sent from the account displayed in the **From** section of the `/sign` user interface. Not displaying this clearly can be considered a security flaw.

In the PR, the wallet does not show the error state [here](https://user-images.githubusercontent.com/5934188/151179186-7a0d9c51-a52b-46c6-a11c-c078bc38d7d3.png) when the `signerId` is not found. Nothing is done (the active account remains selected) and the user can simply use the account selector to select an account and approve the transaction. Another possible option is to display an error state and then force the user to either select an account from what they have available or import an account in order to proceed.

Would appreciate any input on the reasoning here and any suggested modifications to be made to #2401. 

cc: @MaximusHaximus

**Comment by MaximusHaximus** [comment]
@esaminu Thanks for the clear write-up <3

It's worth noting that adding an error state that _blocks_ the user from approving the transaction with a logged in account would be a narrowing change, thus a breaking change to our wallet API interface for the `/sign` route. 

However, I think that if the dapp is requesting that a TX be executed by a specific account ID, then allowing the user to select a totally different account could have hard-to-reason about side-effects/consequences.  For example, what if the TX is submitted and succeeds for a _different_ account ID than is logged into the DAPP, and now the dapp interface is broken and the user can't figure out where the token they just purchased was transferred to without reading through transactions in explorer for the account that was active in the wallet UI when they clicked the approve TX button?

**I think that this boils down to one question:**
_Do we consider allowing users to switch to any account other than the one that the incoming TXs were composed to be signed with a 'feature', even knowing that in some cases it could result in inconsistent dapp state/confusing repercussions?_

**If **YES**, this is a feature:**
- I vote that we do not show _any_ error or warning state, even if the `signerId` requested by the app is not currently imported into the wallet UI (this matches current behaviour).
- If we want to warn the user about possible unexpected consequences of signing the TX with an account other than the DAPP provided as `signerId`, but we consider the ability to do that a feature, then I vote that we display a **warning** state  that tells the user that the incoming request was composed for an account that is not available in their current wallet, but _not_ blocking the user from still going ahead with the transaction if they want to execute it for a different account than the `signerId` asked for.

**If **NO**, this is NOT a feature:**
- I vote that we show a **blocking error state**  that tells the user the incoming request cannot be completed because it was composed for an account that is not available in their current wallet, and that they must add the requested account ID to their wallet to sign the transaction.

**Comment by corwinharrell** [comment]
If a dApp has composed a transaction for a specific address, I believe the wallet **_should not_** allow the user to sign that transaction with any other address.

In this scenario, if the user triggers a transaction from a dApp and is redirected to the wallet only to find that the address being called has not been imported, I believe we should show an error state similar to the one shared above that explains the conflict and allows the user to import the account if they so choose. If imported successfully, we could take the user to teh transaction approval screen immediately following the account import. We could also display an option to "Return to dApp" that allows the user to nullify the transaction, if they decide they want to log into the dApp and reinitiate the transaction with a different address for example.

I fail to see a strong justification for the alternative. If a dApp intends and is requesting for a signature from a specific account, then why should we ignore that request and try and "force through" a signature using a different account, especially when the consequences are likely to mean a broken dApp experience or an error encountered when the user returns to the dApp? If there is a clear and practical use-case that I am just not privy to I'm keen to understand more.

**Comment by Patrick1904** [comment]
Closing as issue is outdated
