### ISSUE TITLE
Disable 2FA script question

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#2496]
Observing https://github.com/near/near-wallet/pull/2487/files#diff-af1599f511c250583625e7629817717180c2b3693cb7d8727d2c9250e612fd6cR22 - which contact is been deployed?

Also why is contract been deployed for disabling 2FA?
My expectation that next sequence of actions are done:
 - remove functional access key and replace them back with full access keys except for the one by NEAR Wallet
 - deploy state cleaning contract
 - call it to clean state after 2FA contract
 - deploy empty contract (to get to 0x0 hash)

Also if account had a contract before, a special circumstances are applied and probably should be done manually:
 - lookup old contract before by finding a offending transaction and it's block
 - fetch the old contract code via next command `http post http://rpc.mainnet.near.org/ method=query params:=‘{“account_id”: “pool.near”, “request_type”: “view_code”, “block_id”: [59131110](tel:59131110) }’ jsonrpc=2.0 id=123` (need to replace block_id to before deployment and account id to the specific account)
 - deserialize the resulting base64 encoded file into .wasm file
 - deploy that contract by using the key from the seed phrase (`near deploy <account id> decoded.wasm --seedPhrase='...'`)
 - replace functional access keys with full access keys except for one by NEAR Wallet (`near keys <account id>`, `near add-key <account id> <key> --seedPhrase='...'`)
 -

**Comment by esaminu** [comment]
@ilblackdragon #2487 is meant to solve a specific case where some users have a seedphrase but they have a bricked 2fa. When they import account via seedphrase, the wallet detects that they have a multisig deployed and adds a LAK leaving them in the same state as before (unable to sign transactions due to bricked multisig). The idea was to provide this script to disable 2fa the same way the wallet does and then the next time they import via seedphrase the wallet would add a FAK since it identifies this as the empty contract the wallet currently uses and assumes the user has disabled 2fa. There is the option of providing documentation for them to run via `near-cli` instead of a script as well.

There is an upcoming PR that will address the issues in #2261. The flow we are considering for disabling 2fa is as you described though the wallet will still use the same contract wasm it currently uses (it's an [arg](https://github.com/near/near-api-js/blob/master/src/account_multisig.ts#L236) in near-api-js). We will also add some gating based on whether the contract has existing state and if it's serializable as multisig before deploying the multisig when enabling 2fa.

**Comment by esaminu** [comment]
@ilblackdragon https://github.com/near/near-wallet/pull/2487 is meant to solve a specific case where some users have a seedphrase but they have a bricked 2fa. When they import account via seedphrase, the wallet detects that they have a multisig deployed and adds a LAK leaving them in the same state as before (unable to sign transactions due to bricked multisig). The idea was to provide this script to disable 2fa the same way the wallet does and then the next time they import via seedphrase the wallet would add a FAK since it identifies this as the empty contract the wallet currently uses and assumes the user has disabled 2fa. There is the option of providing documentation for them to run via near-cli instead of a script as well. Not sure if we should update the script to fetch the old contract code but that may be the best approach here since the script will be useful to whoever is providing support so they don't have to execute the steps manually and can just provide `block_id`, `accountId` and `seedPhrase`. cc @MaximusHaximus 

There is an upcoming PR that will address the issues in https://github.com/near/near-wallet/issues/2261. The flow being implemented for disabling 2fa is as you described though the wallet will still use the same contract wasm it currently uses (it's an [arg](https://github.com/near/near-api-js/blob/master/src/account_multisig.ts#L236) in near-api-js). We will also add some gating based on whether the contract has existing state and if it's serializable as multisig before deploying the multisig when enabling 2fa.
