### ISSUE TITLE
Wallet helper bug with the account state 

### ISSUE THREAD

**Issue by zavodil** [near/near-wallet#2536]
**Problem**

Some accounts like `alex.near` throws an console error while reading the account state

https://helper.mainnet.near.org/account/walletState/alex.near => `Could not find account with accountId: 'alex.near'`

It leads to several bugs. I can't issue access key because of this: dApp redirects to the wallet and wallet throws an error because it can't load account state.

State can be read without issues with CLI (`near state alex.near`)

**Comment by stefanopepe** [comment]
We added it to the backlog, will get back to you asap.

**Comment by zavodil** [comment]
![Screenshot 2022-03-22 at 3 18 48 AM](https://user-images.githubusercontent.com/38926321/159388415-19e17670-a04e-470c-ab85-68f58c7b11ad.png)

error message for this case

**Comment by andy-haynes** [comment]
It doesn't look like we reference this endpoint anymore. The constraint around requiring that an account exists was primarily tied to funded accounts, which have been deprecated. Now that we've migrated from Postgres to DynamoDB we actually no longer have a good use for that `accounts` table at all.

The original issue was definitely problematic and a data issue related to not having a single source of truth, but since moving away from funded accounts I believe these kinds of issues should no longer come up.

@zavodil I'm inclined to close this for now since the behavior responsible for this bug has been deprecated, but please feel free to re-open or continue discussion if you think there's still an issue here.
