### ISSUE TITLE
Able to create an Account without seed phrase or mobile back-up

### ISSUE THREAD

**Issue by AnaisUrlichs** [near/near-wallet#254]
**Problem**
I went through the steps to create an account; however, I just clicked through to the mobile option, then to the previous windows. My account got created even though I did not go to the seed phrase site nor did I put in my phone number.

**Expected Behavior**
The account should have not been created, now I cannot recover it. This will either end up with a bunch of dead/unrecoverable accounts (every time people don't complete the flow); or even worse, users may assume the account was created correctly and use it but then are not able to recover the funds etc. 

(Maybe this is done on purpose -- seems quite risky to me)

**Steps to reproduce**

1. Create a new name
2. Click to the recovery page
3. Go back in your browser history or close the tab/browser and reopen the wallet
4. The account should have been created without recovery

**Comment by kcole16** [comment]
@vgrichina Can we solve this by waiting to send the batch TX that creates the account until after the user has chosen a recovery method?

**Example Flow**
1. User chooses a username, selects "Next" (change copy from "Create Account")
2. User enters email/phone/goes through seed phrase flow
3. User selects "Create Account", send batch TX

**Comment by mikedotexe** [comment]
I came across this today, too. Bumping this as it's probably important for launch. Some folks use the same handle everywhere (github, twitter, ens) and would be sad if their handle became unrecoverable.

**Comment by Patrick1904** [comment]
I’m wondering if we can/should offer users a lower barrier option to complete signup without having to setup recovery with email/phone/phrase. ‘Setup recovery later’ is one option, but it comes with obvious drawbacks. I see users exploring apps and not wanting to go through the whole wallet signup flow just to continue using the app. We’d probably need email/phone in order to send reminder messages to setup recovery methods if they choose to set it up later.

Any ideas?

**Comment by Patrick1904** [comment]
In addition we can show a persistent above nav banner until user has set up a recovery method.

**Comment by AnaisUrlichs** [comment]
@Patrick1904 it's similar to setting up 2FA "later"; how many people actually do it? We could remind users whenever they enter the wallet, like an info pop-up box, to set-up recovery. However, users might click that away. What do you think?

**Comment by Patrick1904** [comment]
My pov is that we should allow a third, low barrier option (and explicitly state the risk), for users that may be testing out an app. My concern is that if we don't offer a low barrier option, this might be a point where a lot of users drop off and stop interacting with the referring app because of the effort required to continue. Labeling the account as 'not secured' with a persistent banner until a recovery method is set up could be an alternative.

Currently if you have an account already, it's even easier to skip recovery setup because all the nav links are available after creating a username so it's easy to skip the step. And if the user chooses seed phrase, it's easy to just temp copy the phrase and paste a word on the next step. Email/SMS are the most useful but also highest barrier.

I think we'll need to decide to either make it really hard for any user, new or existing, to skip setting up recovery for an account, or explicitly offer a 'setup later' option and show a banner, pop modals, etc to encourage securing the account.

@kcole16 @vgrichina @corwinharrell thoughts?

**Comment by corwinharrell** [comment]
I'm leaning towards providing a low barrier option for new users (email or phone required at minimum, so there is **some** way for them to recover) but then having some sort of clear and explicit indicator that their account is "at risk" and can be made more secure by setting up a seed-phrase (during account creation or after the fact).

I like the idea of having quantified "security levels" (ie Level 1, Level 2, Level 3) which is slightly gamified in the sense that most tech-savvy individuals naturally want the most security possible, so if we make it obvious from the get go that using email/phone is less secure, then there is slight pressure on the user to opt for the more secure option. If the user persists with a less-secure recovery method, the onus is on them, and they take full responsibility, which we can make very clear. I also like the idea of displaying some sort of visual indicator that is visible at all times that shows the security level of the current account, and pushes users towards setting up the most secure option if their current method is less than ideal.

This is something that I think would benefit greatly from testing. I'm scheduling some usability tests for next week for wallet/explorer already, and would be happy to make this a point of emphasis, so we can get feedback on users' most likely behavior instead of building this purely based on our own assumptions. This testing could occur before or after implementation and would simply serve to validate or invalidate our proposed solution. Thoughts?

**Comment by Patrick1904** [comment]
@corwinharrell

I'd love to get some insight into users thoughts when they get to the recovery setup step. Are the options confusing? How do they feel about the different options?

Agree w/ showing account security level.

I wouldn't say that seed phrase is automatically a more secure recovery method than sms/phone - depends how it's being used/stored. Requiring sms/email is imo a high barrier option.

**Comment by corwinharrell** [comment]
@Patrick1904 I agree that not requiring any recovery method from the start is a lower barrier to entry, but IMO is not worth the tradeoff considering the inherent risk. My assumption is that we will inevitably run into scenarios where users who have not set up a recovery method lose access to their accounts. Why wouldn't we make the **minimum** effort to ensure that this doesn't happen?

With that in mind, it seems logical to evaluate the recovery options based on "ease of setup" and default to the option that is the most simple/fast or most preferred by users. Perhaps our initial decision on which method that might be could be informed by data that we currently have in our possession such as the numbers that @vgrichina shared in #wallet:

<img width="584" alt="screen_shot_2020-02-27_at_4 59 45_pm" src="https://user-images.githubusercontent.com/5934188/75572506-e7100580-5a28-11ea-8601-d78eb6b328c2.png">

Then we could follow this initial implementation up with usability testing and validating against feedback from users to determine which methods are in fact preferred. We might even be surprised to find that more prominence placed on seed phrase generation as suggested in https://github.com/nearprotocol/near-wallet/issues/355 might result in users defaulting to that option more frequently than we expect.

**Comment by Patrick1904** [comment]
We also need feedback from app developers to find out what experience they want for their users. Signup vs guest ability, etc. I'm assuming that most serious apps will want to be able to communicate with their users through email/sms and capturing that info separately may be sub-optimal. Users could opt in to share info with the app during our signup, etc.

**Comment by mikedotexe** [comment]
I personally don't see the email backup as taking a long time. I know I am still very sad that I lost my normal handle (mikedotexe) because it became unrecoverable. It would stink if a would-be developer tries it out, "reserves" that handle, and doesn't have recovery. Seems like we would just increase the orphaned accounts. But I'm coming from a very sad place, so maybe I'm not representative.

**Comment by corwinharrell** [comment]
> I personally don't see the email backup as taking a long time. I know I am still very sad that I lost my normal handle (mikedotexe) because it became unrecoverable. It would stink if a would-be developer tries it out, "reserves" that handle, and doesn't have recovery. Seems like we would just increase the orphaned accounts. But I'm coming from a very sad place, so maybe I'm not representative.

I have the exact same experience as I lost my preferred handle as well so I can sympathize.
