### ISSUE TITLE
Near Wallet for local Net

### ISSUE THREAD

**Issue by siddharthteli** [near/near-wallet#2695]
I am willing to setup near wallet for local net. I changed nodelUrl in config/environmentDefaults/testnet.js file. I have two issues now - 

- Wallet extension is .test net which should be .near for local net.
- You must provide a blockNumber within 100 of the most recent block; provided: 65567, current: 90651773, which means by default its looking block height from test network. 

Can you guys help me in setting up near wallet for local net, where i can create account, verify if it already exist on local chain etc.

**Comment by andy-haynes** [comment]
Hey @siddharthteli, currently I don't think we have good support for local development (as I imagine you are now familiar).

I believe the intention here would be to specify `NEAR_WALLET_ENV` as `development` rather than `testnet`. Could you try modifying `config/environmentDefaults/development.js` instead to use the configuration that works for local development? Then you'll need to bundle using the `development` environment, e.g.
```
yarn prebuild
NEAR_WALLET_ENV=development yarn bundle
yarn start
```

If that works for you then we would be grateful if you could submit a PR with those changes to `development.js` so that others can benefit from your efforts.

**Comment by siddharthteli** [comment]
@andy-haynes , Yes i am modifying development.js now. Also,I cannot confirm if local near wallet is working fine, till i have a working local near contract helper & explorer.But whenever I have a  working one  will surely submit a PR.
