### ISSUE TITLE
Minor UI updates to point users towards alternative wallets

### ISSUE THREAD

**Issue by charleslavon** [near/near-wallet#3125]
## Goals 
Improve the discoverability of alternative wallets 

1. Decrease the vertical height of the `A new era for new wallets..` section such that a user does not have to scroll to see part of the following section `Decentralization means strength in numbers.`

<img width="1382" alt="Screen Shot 2024-03-06 at 11 02 56 AM" src="https://github.com/near/near-wallet/assets/1915116/b8abcaf5-55b5-4c7e-9e52-5fb9df50072a">

2. Under `wallet.near.org has been discontinued. Explore a range of user-friendly wallets designed to meet your needs.` Replace the `Learn More` button with a `Discover Wallet` button that is an anchor link to the section `Find the right wallet for you.`

<img width="1344" alt="Screen Shot 2024-03-06 at 11 03 13 AM" src="https://github.com/near/near-wallet/assets/1915116/e551824f-962c-4b01-82c1-0168a22e580f">

**Comment by diogoortega** [comment]
Thank you for the great suggestions, @charleslavon.
Assigning to @nall-near for his thoughts.

**Comment by nall-near** [comment]
Hey @charleslavon! I'll start with some context:
[Original Ticket](https://github.com/near/wallet-experience/issues/11)
[Figma Link](https://www.figma.com/file/BT5BBe4xQTo8ePJ7UUttvw/Post-Transition-Landing-Page?type=design&node-id=1%3A2&mode=design&t=GBJJSXbqiEU7Ixep-1)

This page has two states and serves two main purposes. There is a version to 1) [transfer connected accounts](https://www.figma.com/file/BT5BBe4xQTo8ePJ7UUttvw/Post-Transition-Landing-Page?type=design&node-id=6-24595&mode=design&t=GBJJSXbqiEU7Ixep-4) if a user is still connected to wallet.near, and 2) a version when [no accounts are connected](https://www.figma.com/file/BT5BBe4xQTo8ePJ7UUttvw/Post-Transition-Landing-Page?type=design&node-id=42-2962&mode=design&t=GBJJSXbqiEU7Ixep-4), focused on discoverability vs transferring. It also serves to 1) inform users of the change + reason for the change to wallet.near (some users might come back after a long time) and 2) help users find a new wallet to manage their accounts.

Feedback on your requests:
**Header:** I chose this template based on some other pages floating around near.org, do you have a different one we could use that makes the rest of the page more discoverable, or should we just customize this one? I'm cool with updating this however you want, just strive for consistency :)

**CTA to Discover Wallets:** Great suggestion, had that in an earlier version actually. I'd like to keep `learn more` since the main header copy is about the transition, but I'll add a primary CTA to scroll to the wallets section.

**Comment by nall-near** [comment]
Additional thoughts:

- Should we direct users to ALL the wallets [listed here](https://near.org/nearcatalog.near/widget/Index?cat=wallets)? The wallets on this page reflect what is transfer-capable.
- The `compare wallets` button takes users to a spreadsheet with an exhaustive list of features, maybe one day we could embed this content directly on our site (some [old ideas here](https://www.figma.com/file/FNtU2zIXEaMPuXaZDvK3IT/Wallet-Transition?type=design&node-id=3332%3A33496&mode=design&t=ZufcMmzepkkDPEai-1))
- At a certain point, we should update this page even further away from "where is NEAR wallet?" content.

**Comment by charleslavon** [comment]
@nall-near  https://near.org/ecosystem is an example of a header image that is slightly smaller vertically, revealing a different style of content below without requiring a scroll.

**Comment by charleslavon** [comment]
> * listed here

I like that suggestion, perhaps we include a link to All Ecosystem Wallets someone on our wallet.near.org page.

**Comment by jackson-harris-iii** [comment]
@charleslavon I think this ticket it closed after speaking w/ @calebjacob, reviewing the [figma](https://www.figma.com/file/BT5BBe4xQTo8ePJ7UUttvw/branch/998YOmuVtihbkgmbG02wo0/Post-Transition-Landing-Page?type=design&node-id=1-2&mode=design) and [wallet.near.org](wallet.near.org)

This pr [3128](https://github.com/near/near-wallet/pull/3128) seems to have handled the work

**Comment by charleslavon** [comment]
hey @jackson-harris-iii there is still design work to be implemented here.  

1. For users with no existing wallet connection, when visiting wallet.near.org the `Transfer Accounts` button should be `Explore Wallets` which scrolls down to the `Find the right wallet for you.` section
2. The height on the initial view of wallet.near.org should be decreased such that it is similar to https://near.org/ecosystem which makes visible a portion of distinct color of the content below the header without requiring the user to scroll.

**Comment by jackson-harris-iii** [comment]
Closed by: https://github.com/near/near-wallet/pull/3136
