### ISSUE TITLE
"Setup Later" option during account creation

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#415]
## Story

As a user, I want to delay setting up account recovery, so I can determine if I actually want to use NEAR and it's applications before taking more steps.

## Acceptance Criteria

- [ ] Selecting "Setup Later" during the recovery step redirects user past the recovery flow
- [ ] If user opted to skip recovery, a banner appears at the top of their screen with "Your account is at risk! Enable a recovery method in 'Profile'"

## Design
[Figma Doc](https://www.figma.com/file/BhrKSEYsyegyZ0jKsFJ3QR/NEAR-Wallet?node-id=63%3A258)

**Comment by corwinharrell** [comment]
@Patrick1904 I've attached a link to the issue description here with the mockups for mobile. Since we'd be introducing a new modal component for this feature I'll go ahead and do the desktop version as well since the width and positioning of the component in that context will differ slightly. Look out for that soon.

**Comment by corwinharrell** [comment]
@kcole16, Patrick mentioned that you guys had discussed potentially implementing this feature soon, so I just wanted to chime in here to share some of my persisting thoughts and concerns around this as I'm still very much on the fence.

First to highlight the pros/cons as articulated in slack as well as in the thread here: https://github.com/nearprotocol/near-wallet/issues/254 just in an effort to convey them succinctly:

### Pros
- Users would be able to create accounts and test applications with which our wallet is integrated, without needing to endure the friction of setting up a recovery method.

### Cons
Should users lose access to their account before setting a recovery method...
- ... they are at risk of loosing their chosen account name.
- ... they are at risk of losing any and all funds kept in their account.

### Open questions
- _Should we assume the responsibility of allowing users to preview/experience certain features of a 3rd party application, at the expense of putting their accounts at risk in the ways mentioned above?_

In other words, can a third party application assume this responsibility instead, while we maintain a minimum level of security required for use of the NEAR wallet?

@jakestutzman made an analogy earlier that I thought posed a good point:
> Do current financial applications that enable the store of value allow users to create accounts that carry this kind of inherent risk? Do banks allow you to test out accounts with the risk that you might lose access to the funds within should you lose access to your device?

I realize the parallel here is not 1 to 1, but I thought it was thought provoking nonetheless. The flack that I think would have to be endured in the scenario of an account loss due to the absence of a recovery method seems like it may not be worth the tradeoff IMO 🤔 

---

After considering all of the above, I personally can't justify the implementation of a feature like this based purely on an assumption that it will make a marked improvement on the experience that outweighs the risk it introduces.

I'm still of the opinion that something that carries this kind of inherent risk should be tested and only implemented in a scenario where it has been explicitly expressed as a need by existing users with a full comprehension of the risk involved. (I realize we haven't yet had the opportunity to do this kind of validation yet)

My recommendation is to hold off on implementation of the option to skip recovery setup and to at least require setup of a single recovery method in order for an account to be created. I'm curious to hear if there are justifications for arguments against this in addition to the ones outlined above.

Do we feel comfortable and confident implementing something like this as a collective? Where does that confidence originate from and does it outweigh these concerns? Would we benefit from including others on the team in this discussion?

cc @Patrick1904 @vgrichina

**Comment by kcole16** [comment]
The prospect of "losing their chosen account name" actually seems the riskiest to me. It's not a massive risk (as they will initially just be `.near` names, and users will have other opportunities to get their desired name), but burning a bunch of names isn't great.

If we do allow "Setup Later",  we'll need to make it very clear that there is a risk to opting out of recovery, and ideally notify users this risk repeatedly (by persistent banner, popups, etc).

Perhaps we should consider the approach @evgenykuzyakov suggested where we generate a random account name for users, with no recovery, for testing purposes. Though this will require some research re: how users "upgrade" their account.

**Comment by Patrick1904** [comment]
Closing as issue is outdated
