### ISSUE TITLE
Change input background color

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#546]
### Overview
We've received significant feedback that the input box appears disabled due to the gray background. This is especially apparent on `/create`, as the "Submit" button is actually disabled until the user enters a valid name.

### Acceptance Criteria
- [ ] Input background is white when enabled, gray when disabled
- [ ] On desktop, the `/create` input is autofocused

**Comment by Patrick1904** [comment]
@corwinharrell do you have any thoughts on this?

**Comment by corwinharrell** [comment]
Yep, I'm in total agreement. This is something that I was planning on addressing anyways when it came time to make changes as a part of the new component library work. How would the team feel if we went ahead and did a small rework of the default/hover/and focus states for our text inputs? The work would be limited to CSS changes so pretty low lift.

@Patrick1904 mind if I just went in and did this on a new branch?

**Comment by corwinharrell** [comment]
I already have some options for us to consider that do a much better job of distinguishing the different state, and are not too far off from our current styles:

<img width="345" alt="Screen Shot 2020-05-13 at 10 12 48 AM" src="https://user-images.githubusercontent.com/5934188/81823563-7003ec80-9502-11ea-82c7-aeed4560b63e.png">

**Comment by Patrick1904** [comment]
I like this a lot. Couple of questions:

1. Is there a focused error/success state or not necessary? (See that focused has outline)
2. For error case, does clicking the x empty the input?
3. Will the focused input work well for email/phone inputs on `/set-recovery`? Blue on blue etc. Could adjust border color of focused recovery option.
4. We currently have three cases where we show error, checking, and success state (`/create`, `/send-money`, `/recover-seed-phrase`), where we show status label, but no error/success icons. May need to adjust? Generally I'd only show label in error case, but need to show checking and success right now since we can't fit icon because of TLA and flag.

The best solution might be to change placement of TLA and flag dropdown. Flag could be placed on left-side of input, but TLA would need to be after input value. We could make TLA a non-removable suffix (believe you had a design for that), if you think it's as good (or better) UX than right-side placement. But can't change the color of the suffix unfortunately since it's all part of input value and I can't select just that part and wrap it in a span etc. And the 'TLA info' part could be placed somewhere around the input for users to click on and learn more about TLA's. Just ideas.

We don’t have to fix/answer all above (right now) to implement an imperfect version. But would be nice :) I can provide all variations of our current inputs if that’s helpful too.

**Comment by Patrick1904** [comment]
Closing this as styling issues around inputs have been solved.
