### ISSUE TITLE
Add Ledger to account

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#548]
### Story

As a user with a Ledger Nano S, I want to use the Ledger to custody my NEAR account key, so I can more securely store up to $10k worth of assets.

### Proposed User Flow
1. User selects "Add Ledger Nano S to Account" in `/profile`
2. Redirected to `/setup-ledger`
3. Views instructions (see below) for installing Ledger app, completes installation (on Ledger)
4. User is prompted to connect Ledger via USB, open the NEAR app
  i. If error, "Connection failed. Please check that you have the NEAR app open"
5. User is asked "Would you like to remove your other Full Access Keys?"
  i. If yes, add Ledger key, remove other Full Access Keys
  ii. If no, add Ledger key
6. Redirected to `/profile`

### Notes
Pretty good example of a Ledger flow from MyCrypto: https://beta.mycrypto.com/add-account/ledger_nano_s

**Likely instructions to install Ledger App**
1. Open Ledger Live and go to Settings (gear icon on the right):

![](https://raw.githubusercontent.com/cosmos/ledger-cosmos/master/docs/img/cosmos_app1.png)

2. Enable developer mode (last option):

![](https://raw.githubusercontent.com/cosmos/ledger-cosmos/master/docs/img/cosmos_app2.png)

3. Now go back to manager and search for NEAR:

![](https://raw.githubusercontent.com/cosmos/ledger-cosmos/master/docs/img/cosmos_app1.png)

**Comment by corwinharrell** [comment]
@kcole16 When do we plan to support other hardware wallets besides Ledger? I ask incase it makes sense to use language like "Connect Hardware Wallet" vs "Add Ledger S" to make things a little bit more flexible and future proof.

**Comment by corwinharrell** [comment]
Also, do we anticipate ever wanting to offer this option as a part of onboarding rather than after the fact?

**Comment by kcole16** [comment]
@corwinharrell 
> When do we plan to support other hardware wallets besides Ledger?
We do not have any current plans for this, and realistically will be a at least a few months before we get to it. We should use Ledger-specific language for now.

> Also, do we anticipate ever wanting to offer this option as a part of onboarding rather than after the fact?
Yes, we should add it to onboarding pretty much immediately after we finish this flow.

**Comment by corwinharrell** [comment]
@kcole16 Here's a v1 flow for the wallet. If you could do a quick check to see if anything sticks you that would be great. I could a stab at copy and language, but I'm sure we'll want to collaborate as a team to determine what language is most appropriate for any given step.

<img width="1679" alt="Connect Ledger Flow" src="https://user-images.githubusercontent.com/5934188/81603114-c86caa00-939b-11ea-90eb-fd743c2fa407.png">

A couple questions I have:

1. When giving the option to the user to either keep or remove their existing full access keys after connecting their Ledger, is there a particular option we would like to push them towards, or is the decision pretty neutral and based on preference? If this is the case, maybe we should change the treatment of the those options so that it doesn't convey a primary vs secondary option.

2. Is custody of an account key that is granted to a Ledger device limited to a single user name? Am I able to use a ledger device to secure the account keys for multiple accounts? Is this something we need to account for here?

3. What does it look like for a user to disable/disconnect a Ledger device from their account if they have removed all pre-existing keys?

**Comment by vgrichina** [comment]
Note that Ledger app will also require you to confirm public key access (when you connect), so we might want to mention this in copy.

**Comment by vgrichina** [comment]
When removing keys I think we need to mention that other key recovery options are also affected. Like since that point you’d only be able to use ledger to recover account (or seed phrase used to setup ledger).

**Comment by vgrichina** [comment]
1) We should steer user towards removing keys as otherwise they won’t have full security. However user needs to understand the consequences as there is no way recover if ledger key is lost. 
2) It’s not limited, but right now we are using the same public key and so it will be revealed that multiple accounts are controlled by single Ledger. There is a way around it – basically we can have keys with separate “index”, but it’s open question what’s best way to manage it. 
3) we shouldn’t let user do this, unless they set up other full access keys.

**Comment by Patrick1904** [comment]
Just some thoughts. ‘Remove all other full access keys’ probably works for the pro ledger user, but don’t think we should assume that. Would other full access keys be recovery options and devices? If so, option to ‘disable all other recovery methods’ and ‘log me out on all other devices’. But at the same time, it’s easy for me to simply disable a recovery method post ledger flow, and as a user I’d prefer that. I want to feel like I have full control, wouldn’t want to risk losing access, etc.

**Comment by vgrichina** [comment]
@Patrick1904 i agree that copy should be more user friendly than remove all full access keys.  I think we discussed with @kcole16 before that it basically makes sense to replace mentions of keys by one of:
- devices (full access keys)
- recovery methods (full access keys)
- apps (limited access keys)

However I think that we need to offer option to remove access from all other devices specifically because user is not necessarily tech savvy. Holding full access keys without secure hardware can be a liability, so we need to find a good flow to get users to remove the keys but at the same time avoid doing it accidentally without backing up ledger seed phrase, etc.

**Comment by corwinharrell** [comment]
Awesome thanks for the feedback @vgrichina @Patrick1904. I agree with all of the above and appreciate the additional context. I'll take all this into account for the next revision 👍

**Comment by corwinharrell** [comment]
> @Patrick1904 i agree that copy should be more user friendly than remove all full access keys. I think we discussed with @kcole16 before that it basically makes sense to replace mentions of keys by one of:
> 
> * devices (full access keys)
> * recovery methods (full access keys)
> * apps (limited access keys)
> 
> However I think that we need to offer option to remove access from all other devices specifically because user is not necessarily tech savvy. Holding full access keys without secure hardware can be a liability, so we need to find a good flow to get users to remove the keys but at the same time avoid doing it accidentally without backing up ledger seed phrase, etc.

@vgrichina @Patrick1904 one thing to keep in mind is that during the ledger setup process, the on-boarding experience does emphasize the importance of recording and keeping your recovery phrase. So ideally the user would have already done this before enabling their Ledger with the NEAR wallet. That being said, I'm still going to make sure to mention that as a confirmation step after the user elects to remove their previously enabled recovery methods.

**Comment by jakestutzman** [comment]
@corwinharrell will probably want to specify that they can only use the 'Nano S' (if that's still a constraint). Also, maybe explore a version that actually uses the ledger hero shot. Might be nice to show them some love within our wallet? 
![image](https://user-images.githubusercontent.com/46854/81727951-548bd980-944f-11ea-8534-0f0c2e87f592.png)

**Comment by corwinharrell** [comment]
@jakestutzman @kcole16 Perhaps I missed the Nano S constraint? I saw it in the description but couldn't think of a reason why someone would be able to use the S and not the X? If this is true could someone elaborate as to why that is?

Also @jakestutzman , I'm happy to use images, but this would be the first instance of a photographic element in any of our products, so I decided to instead go with an iconographic depiction for consistency's sake. Thoughts?

**Comment by corwinharrell** [comment]
Here is a demo of the next iteration of the flow. I will share the Figma link in a bit once I've done some clean up so we can collaborate on the copy, which I think is one of the trickier but more important elements of this feature.

![Connect Ledger](https://user-images.githubusercontent.com/5934188/81752684-f75c4c00-947f-11ea-9ff7-41597b324482.gif)

**Comment by corwinharrell** [comment]
Here is the [link](https://www.figma.com/file/BhrKSEYsyegyZ0jKsFJ3QR/NEAR-Wallet?node-id=268%3A4933) to the Figma file. Let's collaborate around copy and language in the `Primary UI` section (Press `C` to enter comment mode).

**Comment by Patrick1904** [comment]
Potential Ledger recovery flow:

1. User navigates to `/recover-account`
2. Selects ‘Recover with Ledger’
3. We instruct user to connect ledger (not sure about additional steps)
4. Wallet reacts to Ledger recovery initiated (spins):
    1. We look up all accounts with specific key
        1. If one matching account -> send to dashboard
        2. If more than one matching account -> have user select one or several accounts (or all) to recover -> send to dashboard (which account to set as current/active?)

Thoughts?

**Comment by corwinharrell** [comment]
@Patrick1904 attaching this desktop modal example for reference. Happy for you to eyeball most of it, margins/padding don't need to be exact.

For the animation. I'm thinking of animating `transition: translateY(-16px)` to `transition: translateY(0px)`, and then opacity from `0` to `1`. I have the animation duration at `300ms`. Clicking outside of the modal would dismiss the modal, and the transparent modal container would also have its opacity animate in at the same speed as the modal itself. Pretty basic. There is a small hover state for the close button on desktop.

Key differences between the desktop and mobile are the positioning. Mobile is positioned at the bottom with `justify-content: flex-end` whereas the desktop version is centered. The border radii are also different on mobile to mimic the native iOS action sheet. Let me know what you think:

![modal_animation](https://user-images.githubusercontent.com/5934188/82237360-81366a00-9903-11ea-9beb-5df24b59b263.gif)

Taking a look at your proposed recovery flow.

**Comment by corwinharrell** [comment]
@Patrick1904 re: your proposed recovery flow, Just a few things to note:

- In order to unlock their ledger, the user must enter their ledger pin on the device itself. (This is independent of anything in our wallet, just thought it might be worth mentioning).

For a user to recover their NEAR wallet account via their ledger, will they be required to input their seed phrase at any point? cc @vgrichina @kcole16 

Also @kcole16 any clarification available on the Ledger Nano S constraint?

**Comment by kcole16** [comment]
@Patrick1904 @corwinharrell Re: recovery flow and the next step for the Ledger integration: https://github.com/near/near-wallet/issues/589

Also @corwinharrell, still not 100% clear on Nano S vs. X, but my guess is they will both work. Will test this out though. Thoughts @vgrichina ?

**Comment by corwinharrell** [comment]
Looking to preview the error thrown when trying to connect to ledger via the wallet when my device is not plugged in. @Patrick1904 how long does the wallet attempt to connect before it considers the connection a failure?
