### ISSUE TITLE
Create separate brand for the wallet

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#601]
Currently Wallet is branded as "NEAR" as it was designed as a reference wallet.
Going forward we want Wallet to become it's own product. 

Which means Wallet ideally should have it's own product name and domain (especially given we link localStorage to domain).

**Comment by vgrichina** [comment]
By it’s own name you mean you don’t want it affiliated with NEAR or more like it shouldn’t be called Wallet (but something like NEAR Account)?

**Comment by ilblackdragon** [comment]
I would recommend to not have NEAR in the name.
If it's a financial product that we expect people who are not familiar with crypto to use - it should  represent that.

**Comment by kcole16** [comment]
I think we first need to decide on the future of the web wallet.

If we end up turning the web wallet into an example implementation, I think this naming is fine. 

And then we can come up with a name for the new wallet product.

**Comment by ilblackdragon** [comment]
Given @vgrichina suggests to wrap this web wallet into an app to start with - we would need name for that app.
I also thinking that given we are going to have 2FA, we may as well going forward still pair apps with web-based one as well.

**Comment by vgrichina** [comment]
I think it looks like we’d have to be serious about our wallet for at least next 1-2 years. Third-party wallets aren’t very app-ready generally, so if we want to showcase full power of NEAR we’ll have to maintain our own wallet as a product vs just a demo.

**Comment by corwinharrell** [comment]
@ilblackdragon would love to concretely define the goals and intended impact of a change like this. So far I think your comment above is a good start:

> If it's a financial product that we expect people who are not familiar with crypto to use - it should represent that.

A couple questions for clarity:

- Could we not craft the messaging around the wallet to represent this while still being associated with the NEAR brand?
- What are some other reasons we think the organization, as well as the people using it, would benefit from a rebrand?
- What disadvantages come with retaining the NEAR brand?

**Comment by ilblackdragon** [comment]
Here are few reasons why departing from using NEAR brand directly makes sense:
 
Currently most people are familiar with BTC, and somewhat ETH. We are planning to have both of them (via bridges) and more instruments and tools. Even more people are familiar with USD/EUR which I think we should make even more focus on. NEAR will be technology used to build services, e.g. AWS or Google Cloud. Obviously it will introduce $NEAR to them as well, but creating a limiting factor at installation / word of mouth because users need to first understand what NEAR first seems suboptimal. 

E.g. if you know what NEAR is a hear "Let me send you a dollar or BTC from my NEAR wallet" - you will be like, isn't NEAR a protocol? why are you using it for dollars / BTC? 
Or alternative if they don't know about NEAR "I'm using NEAR wallet to earn interest" - people will ask what is NEAR? And I would expect that most people won't be able to answer initially outside of this other blockchain (also given ppl have trouble describing BTC...).

Additionally, we need to move away from `near.org` domain for a highly likely a for profit product. And we need to do it now before MainNet version launch - otherwise we will need to rename product in App Store / again do migration for keys.

**Comment by vgrichina** [comment]
> creating a limiting factor at installation / word of mouth because users need to first understand what NEAR first seems suboptimal.

not sure what this follows from. Do people need to understand what "Cobo" is when they are using "Cobo Wallet"

> isn't NEAR a protocol? why are you using it for dollars / BTC?

won't you still be using NEAR protocol to send wrapped dollars / BTC?

> we need to move away from near.org domain for a highly likely a for profit product. 

We like literally just moved from .com domain there, lol. Why did we do it? 

Also not sure why do you think wallet going to be for profit product? How does wallet itself get revenue? Seems like most existing products are usually bankrolled by someone else who can make money (e.g. Binance running TrustWallet).

**Comment by vgrichina** [comment]
@ilblackdragon did we settle for specific Inc name? If it’s Berry Club – much easier to come up with ideas. Like it can be Berry Wallet or Avocado wallet, or whatever

**Comment by vgrichina** [comment]
TIL that there is "razzleberry" and "bumbleberry" and both basically mean "any berry". Which might be reasonable to derive a name for an app which can be used to send any berries.

**Comment by vgrichina** [comment]
@jakestutzman wonder what do you think on this? Should we have a separate brand for wallet?

**Comment by vgrichina** [comment]
Nearkat wallet

with Nearkat face as icon

**Comment by jakestutzman** [comment]
It seems that there are two key factors in this decision:
1. Will this be a 'for profit' app (and therefore, need to distant from non-profit near)?
2. Will it support 'non-NEAR' currencies?

If we answer yes to those questions, then yes the wallet should have its own brand/domain, etc.

**Comment by corwinharrell** [comment]
Considering the discussion points shared so far, I think it makes sense to go ahead and start thinking about a rebrand for the wallet. I am interested to hear answers to the questions raised above by @jakestutzman and @vgrichina, as I think those would help guide the decision making here.

@ilblackdragon I think so far the most valid point that you raised is not wanting the brand to be tied so tightly to the $NEAR token and the protocol. If we are to support other coins/bridges, and don't want people to necessarily be concerned about it's tie-in to the NEAR brand so that they can focus purely on the utility of the wallet, then I think it makes sense. I also think people coming from other communities would be more likely to test out a wallet that wasn't directly co-branded with a competing L1, especially if there is tech in place to support their preferred tokens via bridge etc.

"_______ Wallet: Brought to you by the team at NEAR Inc (or whatever it's gonna be called)."

**Comment by ilblackdragon** [comment]
@jakestutzman 
1. Probably yes, may be not right away
2. Well, definitely will have integration with Ethereum and going forward might at least BTC. Additionally I would prefer to re-work UI to make stable coins front and center and make NEAR and other volatile tokens a "investment" assets. (somewhat similar to http://showball.app/)

@corwinharrell Second the part that a non NEAR branded wallet may benefit onboarding users from other communities.
Also if we can start building non-wallet messaging (e.g. this is your bank app) even better.

Let's schedule a branding meeting and discuss the details

**Comment by vgrichina** [comment]
A take from AI dungeon:

Wallet names:

1) While some people may not understand the term "wallet", but will be able to identify with a "bank" - I think it's enough. What I mean is that people may not know what a wallet is in a technical sense, but they can easily identify with a "bank account" or "piggy bank".

2) I believe that the majority of people will understand "dollar wallet", "crypto wallet" and even a "DASH wallet" without having to know what is a NEAR token. The concept is easy to grasp.

3) A name that starts with "D" will be consistent with DASH and DOGE https://en.wikipedia.org/wiki/List_of_common_cryptocurrency_abbreviations

4) A short name is desirable to be able to create a memorable domain name and keep it available for easy remembering.

5) NEAR Protocol is about more than just the wallet - it's also about the token, the blockchain and all the tools we build on top of it.

Why not Near Protocol?

This is not the same as the protocol (ETH, BTC) and there is no risk of confusion since they are two different protocols.

Why not Near Token?

It is too narrow and doesn't give any hint about what it really is.

Why not NearDollar?

Same as above - too narrow. It also implies that it's tied to the value of a dollar, which is not necessarily true.

Brand name:

1) "Near" is a word that everyone understands, and they will understand that we have something to do with money. It is easy to remember and it sounds friendly.

2) Near is about payments and savings - you can transfer money to friends and family for free, convert it to 10+ different currencies and save it.

3) Near will be a gateway to access other blockchains - users don't need to buy a specific token or even know what cryptocurrency is. They can start using crypto by using Near, without any risk.

Why not "Near Cash"?

We don't have anything to do with any government. We are not building a "new USD" or "new EUR", we are creating our own technology, that is not controlled by any government.

Why not "Near Bank"?

It doesn't make sense to use the term "bank" since we are not a bank and not trying to act like one. We are creating a technology to transfer money in a fast, cheap and easy way. Also, "Near" is shorter and more memorable.

4) There are so many ways to transfer money nowadays, that most people don't even realize how hard it still is. With Near, people can easily send money to their friends and family and also save it. It's going to be the easiest way to transfer money from person to person, country to country, currency to currency.

Why not "Flooz"?

Flooz was an early cryptocurrency that tried to do something similar, but it failed.

Why not "GreenBacks"?

GreenBacks was an early cryptocurrency that tried to do something similar, but it failed.

Why not "Bitcoin"?

It's already called that.

Why not "DogeCoin"?

It's already called that.
Why not "Wyyyre"?

We don't want to be associated with a specific animal. Also, it doesn't sound very friendly.

Why not "BunnyToken"?

See Wyyyre.

Why not "DoggieCoin"?

See Wyyyre.
Why not "Far"?

It's already called that.
Why not "Bifrost"?

See Wyyyre.

5) Why Near? Because it's short and easy to remember. You can't go wrong with a name like that.

6) We want a brand that sounds friendly and easy to remember.

7) We want a brand that people can associate with money.

8) We want a brand that can be pronounced the same in every language.

9) We want a brand that is pronounceable by computers.

10) We want a brand that doesn't look ridiculous or obscene when abbreviated.

**Comment by agileurbanite** [comment]
At this time we are not looking at creating a separate brand for the wallet.  We might revisit this topic in the future but closing for now.
