### ISSUE TITLE
Add Progressive Web App support

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#676]
There is a good reason for PWA even on desktop for Wallet.
One of the possible attack vector is if the server that serves frontend gets hacked and injects malicious JS.

We are mitigating that with 2FA, but we can also add an extra layer where user can elect to "install" specific version. Then updates can be scheduled, user can check that they have been confirmed by community and optionally wait some time to confirm that there are no vulnerabilities.

More details on PWA in Chrome on desktop:
https://support.google.com/chrome/answer/9658361?co=GENIE.Platform%3DDesktop&hl=en

The upgrades should happen from user's consent. E.g. it will suggest that new version is available, show hash of the code of the new version (that the background worker can verify and confirm), also the update will be sign by the server key, which can also be validated by previous version for authenticity in case of DNS poisoning.

**Comment by kcole16** [comment]
Thoughts on this @Patrick1904 @vgrichina? Seems pretty straightforward to get a basic version of this working (without offline support): https://codelabs.developers.google.com/codelabs/your-first-pwapp/#0

**Comment by vgrichina** [comment]
I'd prefer we don't do it. It is much easier to screw up wallet (in sense in putting it in unusable / unrecoverable state for an average user) if we build PWA interfering with updates. This also makes update rollout pain in the ass without users being able to actually do any meaningful verification anyway (like seriously, whoever would click anything except "Allow update" if we keep asking them). 

I think less invasive things to do would be:
1) make sure we have https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security so that trivial attacks aren't possible
2) for mobile wallets make sure we have SSL certificate pinning 
3) for mobile wallets we can consider either bundling JS/HTML as part of the app bundle (this is trade off in upgradability though) or having native UI for transaction signing (more work to support singing but potentially better UI + easier to upgrade all other parts of wallet if we don't prebuild them).

In any case actual security IMO would need to be provided by some second factor:
- our 2FA service multisig
- Ledger
- native mobile UI for signing

**Comment by vgrichina** [comment]
Maybe we alternatively should deploy on IPFS and use Cloudflare's gateway? https://blog.cloudflare.com/e2e-integrity/
Whoever is super serious about the thing can install browser extension that would verify content hashes are matching.

**Comment by jimmy3dita** [comment]
We ended up putting this one on hold, and approach the issue with alternative solutions (e.g. native apps)
