### ISSUE TITLE
Delegation

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#722]
### Overview
Delegation and staking will be the dominant uses of NEAR until at least Phase 2, and potentially longer (as we see more apps deployed to mainnet). We currently do not have a user-friendly way to delegate, and also want to maximize the utility of the wallet pre-popular apps (and post).

The first version of this can be very similar to Matt's example delegation app: https://github.com/near-examples/delegation-app, as a separate `/delegation` route.

### Stories
As a user, I want to view all of the available validators, their fees, and their staking records, so I can understand my options of who to delegate to.

As a user, I want to delegate in as few steps as possible, so I can easily earn yield on my NEAR.

As a user, I want to clearly view my delegation rewards, so I can understand the profit I've earned from delegating.

As a user, I want to undelegate in as few steps as possible, and understand how long it will take to undelegate, so I can easily unfreeze my NEAR.

As a user, I want to view my currently delegated balance and who it is delegated to, so I can understand the breakdown of my NEAR that is active and delegated.

### Flows
Flow Diagram: https://whimsical.com/73BmnJaf4H3nM717vYZrhP@7YNFXnKbYki95BSqaSZPZ

**Delegate Flow**
1. User navigates to "Delegation" page
2. User views a list of available validators
  a. Name of validator
  b. Fee (% of reward)
  c. URL
3. User clicks "Delegate" button next to validator they want to delegate to
4. User enters amount to delegate and clicks "Submit"
5. User must enter their account name, then select "Confirm" to send TX
  a. If successful, user receives message "You've successfully delegated <amount> to <validator name>"
6. User views delegated amount, validator name, and earned NEAR on the "Delegation" page

**Undelegate Flow**
1. User navigates to "Delegation" page
2. User selects "Undelegate" button
3. User must enter their account name, then select "Confirm" to send TX
  a. If successful, user receives message "You've successfully undelegated <amount>. Your NEAR will be unlocked in <time>"

### NOTES
Matt's example delegation app: https://github.com/near-examples/delegation-app

**Comment by mattlockyer** [comment]
Biggest issue will be maintaining:
- list of validators
- stats on validators
- anything historical, query support etc...

V0 for OUR wallet should definitely be a list that we control. We could follow @jimmy3dita design for Stake Wars. A repo with list and validators can submit PRs.

**Comment by bowenwang1996** [comment]
For now we can require that they must create the staking pool through the factory deployed by NEAR foundation. In the future we can think about how to do contract auditing.

**Comment by jimmy3dita** [comment]
## UX Issues I have experienced as a delegator

### 1. lock-in period
As a user, I had to understand the lock-in period. Unstaked funds remain locked for three epochs (36 hours on TestNet) before they are available to withdraw. 

*How it worked on the delegation app*
We separated the "locked balance" from the "available balance", and we required users to keep track of the epochs, e.g. by manually set reminders to come back and withdraw

*Nice to have*
Batch available-to-withdraw balance with other transactions, seamlessly.

### 2. Measuring rewards
As a user, I have to`ping` the staking pool to recalculate the rewards and update my yields. This operation is a bit confusing: it is needed once per epoch in order to measure rewards for everyone, and some validators are "pinging" their own staking pools.

*How it worked on the delegation app*
No ping was implemented, the rewards were measured by a simple `view` command, without knowing when the calculation was done

*Nice to have*
Know when the last `ping` was issued, and a button to update the value to "now".

### 3. Owner alerts
As a validator who wants to update the staking pool contract, I have today to manually contact all my delegators, asking them to
1. unstake funds from old staking pool
2. withdraw funds from old staking pool
3. deposit and stake funds to new staking pool

*How it worked on the delegation app*
It had to list two staking pools, and have the user withdraw and stake manually

*Nice to have*
(requires coordination with @evgenykuzyakov) a `migration flag` with the new staking pool address, such that a delegation app can alert the user of the migration flag, and highlight the unstake button.
I suppose this issue will be solved with smart contracts upgradability, so this is a workaround - which may be useful as I see the possibility of multiple updates for our staking pool smart contracts

**Comment by kcole16** [comment]
@jimmy3dita @bowenwang1996 Is 36 hours (3 epochs) to receive unstaked funds the expectation for mainnet as well?

**Comment by kcole16** [comment]
@jimmy3dita Point 3) is likely out-of-scope for the first version of delegation. Points 1) and 2) we will certainly address, as they both seem critical.

**Comment by bowenwang1996** [comment]
> Is 36 hours (3 epochs) to receive unstaked funds the expectation for mainnet as well?

yes. However, epochs can take longer time if some validators are offline.

**Comment by corwinharrell** [comment]
I've added a visual user flow to the epic description for reference if anyone like me find this helpful in visualizing the scope as well as the path travelled:

https://whimsical.com/73BmnJaf4H3nM717vYZrhP@7YNFXnKbYki95BSqaSZPZ

If you find this sort of thing helpful, please let me know as I'd be happy to continue creating these as a part of larger efforts like this to help everyone get oriented and aligned. It also gives people a great place to comment on the flow itself, and to point out if anything is missing or unexpected.

**Comment by corwinharrell** [comment]
@kcole16 With the re-introduction of the stripped down validator profile where the user will manage their stake and rewards, I'm wandering if we want to create an additional issue for "Manage my stake" that includes:

1. View my amount that is pending release from my validator
2. View my list of validators with unclaimed rewards
3. View my list of validators with funds available for withdrawal
4. Claim rewards from a validator
3. Withdraw my funds from a validator/delegation contract

Maybe it makes sense to roll these up into #755? Thoughts @mattlockyer @Patrick1904?

The way I'm thinking about the iterations of this project are as follows, which is slightly different than how the Epic is split up right now:

1. Stake with Known Validator - #753
2. Find a validator (whitelist) - #764 
3. Manage my stake (unstake, claim rewards, withdraw balance) - #755 + ?

**Comment by kcole16** [comment]
@corwinharrell It makes sense to me to add part of the "Manage" scope to #755. 

I definitely think "Claim Rewards" is important, but perhaps it's better to separate that into an additional issue to complete post v1 of undelegate. Which would mean adding 1, 3, and 5 to #755.

Thoughts? cc @jimmy3dita

**Comment by Patrick1904** [comment]
Closing as issue is outdated
