### ISSUE TITLE
Undelegate v1

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#755]
### Overview
Per @jimmy3dita's comments, users will need to send at least 2 TX's,  3 epochs apart to withdraw. They first call `unstake` with the amount to unstake. After 3 epochs, they can call `withdraw` to withdraw their NEAR tokens.

### Proposed Flows
On `/staking`

**Undelegate**
1. User clicks "Unstake"
2. User enters the amount to unstake
3. User must enter their account name, then select "Confirm" to send TX
4. If successful, user receives message "You've successfully unstaked . You will be able to withdraw your NEAR after 3 epochs, roughly 36 hours. "

**Withdraw**
1. User clicks "Withdraw"
2. If successful, user receives message "Your NEAR was successfully withdraw from the staking contract, and is now in your Available Balance"

### Acceptance Criteria
- [ ] If user has NEAR delegated, the "Unstake" button is visible
- [ ] Selecting "Unstake" and entering an amount triggers the `unstake` function 
- [ ] If user has NEAR unstaking, can view message "<amount> NEAR is currently pending, and will be available to withdraw after 3 epochs"
- [ ] If user has NEAR unstaked, and still in the delegation contract, the "Withdraw" button is visible
- [ ] User can withdraw their unstaked NEAR

**Comment by corwinharrell** [comment]
Attaching the flow for `UNSTAKE` here. The flow is _almost_ identical to the staking flow, but there are a few small UI changes to accompany this release:

1. The `UNSTAKE` button should now appear on both the validator profile, as well as the main staking dashboard. Since users can only delegate to a single validator, it improves discoverability and benefits them to be able to take this action from both views. This will change if/when we enable staking to multiple validators, at which point the user will need to unstake from that particular validator's profile.

2. Similarly to the above, the option to `WITHDRAW` should now appear on the dashboard.

3. On the input amount view, there is now a "Use Max" option, that will populate the amount field with the user's available balance (in the case of staking) or total amount staked (in the case of unstaking)

4. On the success screen, let's take an opportunity to educate the user on the fund release restriction. A link here reads "Why do I have to wait?". This can link to our docs, website, or can simply open a tooltip component, depending on what content we have available on the subject and where it currently lives.

@Patrick1904 currently this diagram is our source of truth. Notice that there are a few small design changes to a few components (namely the modal `from` text and success state text alignment (changed to `text-align: center`) I'm working on cleaning up the Figma file to include all the most recent changes. I'll ping you when that is done.

**Comment by kcole16** [comment]
I think we should add something like "Tokens will be available to withdraw 36-48 hours (3 full epochs) after unstaking" to the "You are unstaking" modal as well. Users keep missing that detail, and we really want to hammer it home.

**Comment by corwinharrell** [comment]
@kcole16 @Patrick1904 Updated modal with disclaimer
