### ISSUE TITLE
Sign in with Ledger should not add keys

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#772]
**Problem**
Currently when "Sign in with Ledger" option is selected, Wallet is asking to "Add Key" to each account that has the key from this ledger.

**Expected Behavior**
After "Sign in with Ledger", only once need to confirm giving public key to the Ledger, and it finds and opens all accounts that have this and all subsequent (e.g. with different paths) public keys.

**Comment by kcole16** [comment]
@vgrichina What are your thoughts on this?

**Comment by vgrichina** [comment]
We have to add keys to be able to connect to contract helper.

**Comment by ilblackdragon** [comment]
@vgrichina I don't understand. How is contract helper in this cast used? 
Also I don't understand what key is even added? Like my understanding right now that I exposed my account to attack right now by doing this.

**Comment by vgrichina** [comment]
@ilblackdragon as we don't have any way to store metadata about keys on-chain, we have to store it off-chain (i.e. in contract helper). We also need to authorize access to contract helper somehow.

> Also I don't understand what key is even added right now? Like my understanding at the moment that I exposed my account to attack by adding a new key.

I agree that it should be special cased on Ledger app side to display meaningful message (kinda similar how we do for full access key) instead of raw info about key.

**Comment by ilblackdragon** [comment]
If this is to inform off-chain service, how about we sign a message with Ledger and send it to contract helper? In a way, it's similar how applications in Ethereum asking to authorize them from the wallet.

This way don't need to send anything extra on-chain, and don't need to create extra key which has unclear expectations to the user at this point.

**Comment by vgrichina** [comment]
To implement what you are proposing we'll need to:
- have special support in Ledger app and API to sign such custom message
- user will still have to confirm some weird stuff when connecting Ledger
- the message signed by Ledger will have to be used to obtain another auth token / key (for contract helper)
- contract helper will need additional check whether this auth token / key is still valid (e.g. account could have been transferred on chain to somebody else).

It seems that far easier change is just to make a change in Ledger app to make sure that message reads something like. "Allow connection to web wallet" instead of current low level UI.

**Comment by jimmy3dita** [comment]
moving the discussion to #1536
