### ISSUE TITLE
Add banner to indicate network/RPC issues

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#783]
### Overview
Recent network issues have made the wallet slow/unusable for periods of time. Additionally, some of our error messages are quite vague/misleading in these cases, and we do not warn users that the network may be the underlying issue (e.g. "Invalid Seed Phrase"). 

Adding a banner with a warning and link to nearprotocol.statuspal.io will help provide some indication of what's happening.

Perform health check by calling RPC endpoint `/health`

### Acceptance Criteria
- [ ] When RPC is unresponsive, display a red banner at the top of the page
  - [ ] "Our network nodes are experiencing issues. Please check back later, as you will likely encounter high error rates, including during login. To view the latest network status updates, click here"
  - [ ] Link to nearprotocol.statuspal.io

**Comment by kcole16** [comment]
@bowenwang1996 Is there a good way to perform a network health check?

**Comment by bowenwang1996** [comment]
There is a rpc endpoint for health check `/health`

**Comment by ilblackdragon** [comment]
How about statuspal? We ideally should use something third party

**Comment by Patrick1904** [comment]
@vgrichina @kcole16 here's an example response from Statuspal: `https://statuspal.io/api/v1/status_pages/nearprotocol/status`

![Screen Shot 2020-10-12 at 1 37 47 PM](https://user-images.githubusercontent.com/24921205/95788345-37726580-0c90-11eb-9b5f-80b3fc90cd90.png)

Should we base the network error on all (RPC, Explorer frontend, Explorer) or just RPC?

**Comment by kcole16** [comment]
@Patrick1904 Seems like we should use the RPC endpoint `/health` instead (checking https://rpc.mainnet.near.org), as it's more direct.

**Comment by Patrick1904** [comment]
@vgrichina @bowenwang1996 apparently the RPC /health end point returns an error if the node hasn’t responded with a block for 20 seconds, so AFAIU it may not catch the frequently reported issue with recovering accounts, i.e. ‘no accounts recovered…’

In theory, if 'no accounts recovered...' happened and RPC is unresponsive, would /health return an error?

**Comment by bowenwang1996** [comment]
> In theory, if 'no accounts recovered...' happened and RPC is unresponsive, would /health return an error?

Yeah we will work on tweaking the health endpoint to be more informative but right now that may not return an error

**Comment by marcinbodnar** [comment]
@corwinharrell We should get back to this topic because there is an additional issue now.
I prepared changes available here #1764 , so when the indexer is not responding (like it was several times so far) user will still be able to:
 - sign tx
 - login
 - send money
Even if the other data is not available.

The thing is that in this case, the user will see that the Wallet is not working properly. For example, if the user enters the dashboard will see that balance is loading, recent activities are loading - the user might think that the Wallet is not working at all. I think we should consider informing the user that he can still do some important stuff because it's not obvious (cc @vgrichina ).

**Comment by stefanopepe** [comment]
@marcinbodnar let's open a new issue, and mention this one as previous reference

**Comment by marcinbodnar** [comment]
@stefanopepe done #1803
