### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/near-wallet#889]
### Overview
Users need to log out for various reasons. We need to warn them obnoxiously to make sure they can recover their account before they do so.

### Acceptance Criteria
- [ ] "Logout" is present in the navbar drop down
- [ ] If user has multiple loaded accounts, they are prompted "Would you like to logout from <selected_account> only, or all accounts?"
   - [ ] User can choose either "This Account Only", or "All Accounts"
   - [ ] User can successfully log out from a single account
   - [ ] User can successfully log out from all accounts
- [ ] User is warned with the below warning
- [ ] User must enter their account name before confirming logout

**Warning Copy**

"Warning: Before logging out, please ensure you have at least one recovery method correctly enabled for each of your accounts. Otherwise, you will LOSE ACCESS to your account(s) FOREVER. We HIGHLY recommend testing your recovery method(s) before proceeding."

**Comment by vgrichina** [comment]
> It's expected for security reasons. Especially, if they expect someone might be able to access this device.

In that case I assume you also want to remove the public key for this device altogether?

**Comment by abakuz** [comment]
Please also consider LOG IN button, currently the way to log is via Recover Your Account which is not super intuitive

**Comment by vgrichina** [comment]
If anybody needs to remove the keys from local machine right now you can do it using Chrome dev tools, etc:

https://www.leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/

MAKE SURE YOUR RECOVERY METHOD IS WORKING BEFORE REMOVING LOCAL KEYS

**Comment by kcole16** [comment]
### Overview
Users need to log out for various reasons. We need to warn them obnoxiously to make sure they can recover their account before they do so.

### Acceptance Criteria
- [ ] "Logout" is present in the navbar drop down
- [ ] If user has multiple loaded accounts, they are prompted "Would you like to logout from <selected_account> only, or all accounts?"
   - [ ] User can choose either "This Account Only", or "All Accounts"
   - [ ] User can successfully log out from a single account
   - [ ] User can successfully log out from all accounts
- [ ] User is warned with the below warning
- [ ] User must enter their account name before confirming logout

**Warning Copy**

"Warning: Before logging out, please ensure you have at least one recovery method correctly enabled for each of your accounts. Otherwise, you will LOSE ACCESS to your account(s) FOREVER. We HIGHLY recommend testing your recovery method(s) before proceeding."

**Comment by garikbesson** [comment]
Are there any updates here? People still need to be able to log out.

**Comment by max-block** [comment]
Maybe it's a good idea to ask users input seed words before logout. Users can ignore a warning message, but if they are able to input seed words it means they really have a backup of it.

**Comment by Patrick1904** [comment]
Closing as issue is outdated
